<?php

use Illuminate\Database\Seeder;
use PocketByR\Departamento;
use PocketByR\Ciudad;
class DatabaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // $this->call(UsersTableSeeder::class);
    	Departamento::create(['id' => '1' , 'nombre' => 'Amazonas']);
		Departamento::create(['id' => '2', 'nombre' => 'Antioquia']);
		Departamento::create(['id' => '3', 'nombre' => 'Arauca']);
		Departamento::create(['id' => '4', 'nombre' => 'Atlántico']);
		Departamento::create(['id' => '5', 'nombre' => 'Bolívar']);
		Departamento::create(['id' => '6', 'nombre' => 'Boyacá']);
		Departamento::create(['id' => '7', 'nombre' => 'Caldas']);
		Departamento::create(['id' => '8', 'nombre' => 'Caquetá']);
		Departamento::create(['id' => '9', 'nombre' => 'Casanare']);
		Departamento::create(['id' => '10', 'nombre' => 'Cauca']);
		Departamento::create(['id' => '11', 'nombre' => 'Cesar']);
		Departamento::create(['id' => '12', 'nombre' => 'Chocó']);
		Departamento::create(['id' => '13', 'nombre' => 'Córdoba']);
		Departamento::create(['id' => '14', 'nombre' => 'Cundinamarca']);
		Departamento::create(['id' => '15', 'nombre' => 'Güainia']);
		Departamento::create(['id' => '16', 'nombre' => 'Guaviare']);
		Departamento::create(['id' => '17', 'nombre' => 'Huila']);
		Departamento::create(['id' => '18', 'nombre' => 'La Guajira']);
		Departamento::create(['id' => '19', 'nombre' => 'Magdalena']);
		Departamento::create(['id' => '20', 'nombre' => 'Meta']);
		Departamento::create(['id' => '21', 'nombre' => 'Nariño']);
		Departamento::create(['id' => '22', 'nombre' => 'Norte de Santander']);
		Departamento::create(['id' => '23', 'nombre' => 'Putumayo']);
		Departamento::create(['id' => '24', 'nombre' => 'Quindo']);
		Departamento::create(['id' => '25', 'nombre' => 'Risaralda']);
		Departamento::create(['id' => '26', 'nombre' => 'San Andrés y Providencia']);
		Departamento::create(['id' => '27', 'nombre' => 'Santander']);
		Departamento::create(['id' => '28', 'nombre' => 'Sucre']);
		Departamento::create(['id' => '29', 'nombre' => 'Tolima']);
		Departamento::create(['id' => '30', 'nombre' => 'Valle del Cauca']);
		Departamento::create(['id' => '31', 'nombre' => 'Vaupés']);
		Departamento::create(['id' => '32', 'nombre' => 'Vichada']);

		Ciudad::create(['id' => '1', 'idDepartamento' => '1' , 'nombre' => 'leticia']);
		Ciudad::create(['id' => '2', 'idDepartamento' => ' 1', 'nombre' => 'Puerto Nariño']);
		Ciudad::create(['id' => '3', 'idDepartamento' => ' 2', 'nombre' => 'Abejorral']);
		Ciudad::create(['id' => '4', 'idDepartamento' => ' 2', 'nombre' => 'Abriaquí']);
		Ciudad::create(['id' => '5', 'idDepartamento' => ' 2', 'nombre' => 'Alejandria']);
		Ciudad::create(['id' => '6', 'idDepartamento' => ' 2', 'nombre' => 'Amagá']);
		Ciudad::create(['id' => '7', 'idDepartamento' => ' 2', 'nombre' => 'Amalfi']);
		Ciudad::create(['id' => '8', 'idDepartamento' => ' 2', 'nombre' => 'Andes']);
		Ciudad::create(['id' => '9', 'idDepartamento' => ' 2', 'nombre' => 'Angelópolis']);
		Ciudad::create(['id' => '10', 'idDepartamento' => ' 2', 'nombre' => 'Angostura']);
		Ciudad::create(['id' => '11', 'idDepartamento' => ' 2', 'nombre' => 'Anorí']);
		Ciudad::create(['id' => '12', 'idDepartamento' => ' 2', 'nombre' => 'Anzá']);
		Ciudad::create(['id' => '13', 'idDepartamento' => ' 2', 'nombre' => 'Apartadó']);
		Ciudad::create(['id' => '14', 'idDepartamento' => ' 2', 'nombre' => 'Arboletes']);
		Ciudad::create(['id' => '15', 'idDepartamento' => ' 2', 'nombre' => 'Argelia']);
		Ciudad::create(['id' => '16', 'idDepartamento' => ' 2', 'nombre' => 'Armenia']);
		Ciudad::create(['id' => '17', 'idDepartamento' => ' 2', 'nombre' => 'Barbosa']);
		Ciudad::create(['id' => '18', 'idDepartamento' => ' 2', 'nombre' => 'Bello']);
		Ciudad::create(['id' => '19', 'idDepartamento' => ' 2', 'nombre' => 'Belmira']);
		Ciudad::create(['id' => '20', 'idDepartamento' => ' 2', 'nombre' => 'Betania']);
		Ciudad::create(['id' => '21', 'idDepartamento' => ' 2', 'nombre' => 'Betulia']);
		Ciudad::create(['id' => '22', 'idDepartamento' => ' 2', 'nombre' => 'Bolívar']);
		Ciudad::create(['id' => '23', 'idDepartamento' => ' 2', 'nombre' => 'Briceño']);
		Ciudad::create(['id' => '24', 'idDepartamento' => ' 2', 'nombre' => 'Burítica']);
		Ciudad::create(['id' => '25', 'idDepartamento' => ' 2', 'nombre' => 'Caicedo']);
		Ciudad::create(['id' => '26', 'idDepartamento' => ' 2', 'nombre' => 'Caldas']);
		Ciudad::create(['id' => '27', 'idDepartamento' => ' 2', 'nombre' => 'Campamento']);
		Ciudad::create(['id' => '28', 'idDepartamento' => ' 2', 'nombre' => 'Caracolí']);
		Ciudad::create(['id' => '29', 'idDepartamento' => ' 2', 'nombre' => 'Caramanta']);
		Ciudad::create(['id' => '30', 'idDepartamento' => ' 2', 'nombre' => 'Carepa']);
		Ciudad::create(['id' => '31', 'idDepartamento' => ' 2', 'nombre' => 'Carmen de Viboral']);
		Ciudad::create(['id' => '32', 'idDepartamento' => ' 2', 'nombre' => 'Carolina']);
		Ciudad::create(['id' => '33', 'idDepartamento' => ' 2', 'nombre' => 'Caucasia']);
		Ciudad::create(['id' => '34', 'idDepartamento' => ' 2', 'nombre' => 'Cañasgordas']);
		Ciudad::create(['id' => '35', 'idDepartamento' => ' 2', 'nombre' => 'Chigorodó']);
		Ciudad::create(['id' => '36', 'idDepartamento' => ' 2', 'nombre' => 'Cisneros']);
		Ciudad::create(['id' => '37', 'idDepartamento' => ' 2', 'nombre' => 'Cocorná']);
		Ciudad::create(['id' => '38', 'idDepartamento' => ' 2', 'nombre' => 'Concepción']);
		Ciudad::create(['id' => '39', 'idDepartamento' => ' 2', 'nombre' => 'Concordia']);
		Ciudad::create(['id' => '40', 'idDepartamento' => ' 2', 'nombre' => 'Copacabana']);
		Ciudad::create(['id' => '41', 'idDepartamento' => ' 2', 'nombre' => 'Cáceres']);
		Ciudad::create(['id' => '42', 'idDepartamento' => ' 2', 'nombre' => 'Dabeiba']);
		Ciudad::create(['id' => '43', 'idDepartamento' => ' 2', 'nombre' => 'Don Matías']);
		Ciudad::create(['id' => '44', 'idDepartamento' => ' 2', 'nombre' => 'Ebéjico']);
		Ciudad::create(['id' => '45', 'idDepartamento' => ' 2', 'nombre' => 'El Bagre']);
		Ciudad::create(['id' => '46', 'idDepartamento' => ' 2', 'nombre' => 'Entrerríos']);
		Ciudad::create(['id' => '47', 'idDepartamento' => ' 2', 'nombre' => 'Envigado']);
		Ciudad::create(['id' => '48', 'idDepartamento' => ' 2', 'nombre' => 'Fredonia']);
		Ciudad::create(['id' => '49', 'idDepartamento' => ' 2', 'nombre' => 'Frontino']);
		Ciudad::create(['id' => '50', 'idDepartamento' => ' 2', 'nombre' => 'Giraldo']);
		Ciudad::create(['id' => '51', 'idDepartamento' => ' 2', 'nombre' => 'Girardota']);
		Ciudad::create(['id' => '52', 'idDepartamento' => ' 2', 'nombre' => 'Granada']);
		Ciudad::create(['id' => '53', 'idDepartamento' => ' 2', 'nombre' => 'Guadalupe']);
		Ciudad::create(['id' => '54', 'idDepartamento' => ' 2', 'nombre' => 'Guarne']);
		Ciudad::create(['id' => '55', 'idDepartamento' => ' 2', 'nombre' => 'Guatapé']);
		Ciudad::create(['id' => '56', 'idDepartamento' => ' 2', 'nombre' => 'Gómez Plata']);
		Ciudad::create(['id' => '57', 'idDepartamento' => ' 2', 'nombre' => 'Heliconia']);
		Ciudad::create(['id' => '58', 'idDepartamento' => ' 2', 'nombre' => 'Hispania']);
		Ciudad::create(['id' => '59', 'idDepartamento' => ' 2', 'nombre' => 'Itagüí']);
		Ciudad::create(['id' => '60', 'idDepartamento' => ' 2', 'nombre' => 'Ituango']);
		Ciudad::create(['id' => '61', 'idDepartamento' => ' 2', 'nombre' => 'Jardín']);
		Ciudad::create(['id' => '62', 'idDepartamento' => ' 2', 'nombre' => 'Jericó']);
		Ciudad::create(['id' => '63', 'idDepartamento' => ' 2', 'nombre' => 'La Ceja']);
		Ciudad::create(['id' => '64', 'idDepartamento' => ' 2', 'nombre' => 'La Estrella']);
		Ciudad::create(['id' => '65', 'idDepartamento' => ' 2', 'nombre' => 'La Pintada']);
		Ciudad::create(['id' => '66', 'idDepartamento' => ' 2', 'nombre' => 'La Unión']);
		Ciudad::create(['id' => '67', 'idDepartamento' => ' 2', 'nombre' => 'Liborina']);
		Ciudad::create(['id' => '68', 'idDepartamento' => ' 2', 'nombre' => 'Maceo']);
		Ciudad::create(['id' => '69', 'idDepartamento' => ' 2', 'nombre' => 'Marinilla']);
		Ciudad::create(['id' => '70', 'idDepartamento' => ' 2', 'nombre' => 'Medellín']);
		Ciudad::create(['id' => '71', 'idDepartamento' => ' 2', 'nombre' => 'Montebello']);
		Ciudad::create(['id' => '72', 'idDepartamento' => ' 2', 'nombre' => 'Murindó']);
		Ciudad::create(['id' => '73', 'idDepartamento' => ' 2', 'nombre' => 'Mutatá']);
		Ciudad::create(['id' => '74', 'idDepartamento' => ' 2', 'nombre' => 'Nariño']);
		Ciudad::create(['id' => '75', 'idDepartamento' => ' 2', 'nombre' => 'Nechí']);
		Ciudad::create(['id' => '76', 'idDepartamento' => ' 2', 'nombre' => 'Necoclí']);
		Ciudad::create(['id' => '77', 'idDepartamento' => ' 2', 'nombre' => 'Olaya']);
		Ciudad::create(['id' => '78', 'idDepartamento' => ' 2', 'nombre' => 'Peque']);
		Ciudad::create(['id' => '79', 'idDepartamento' => ' 2', 'nombre' => 'Peñol']);
		Ciudad::create(['id' => '80', 'idDepartamento' => ' 2', 'nombre' => 'Pueblorrico']);
		Ciudad::create(['id' => '81', 'idDepartamento' => ' 2', 'nombre' => 'Puerto Berrío']);
		Ciudad::create(['id' => '82', 'idDepartamento' => ' 2', 'nombre' => 'Puerto Nare']);
		Ciudad::create(['id' => '83', 'idDepartamento' => ' 2', 'nombre' => 'Puerto Triunfo']);
		Ciudad::create(['id' => '84', 'idDepartamento' => ' 2', 'nombre' => 'Remedios']);
		Ciudad::create(['id' => '85', 'idDepartamento' => ' 2', 'nombre' => 'Retiro']);
		Ciudad::create(['id' => '86', 'idDepartamento' => ' 2', 'nombre' => 'Ríonegro']);
		Ciudad::create(['id' => '87', 'idDepartamento' => ' 2', 'nombre' => 'Sabanalarga']);
		Ciudad::create(['id' => '88', 'idDepartamento' => ' 2', 'nombre' => 'Sabaneta']);
		Ciudad::create(['id' => '89', 'idDepartamento' => ' 2', 'nombre' => 'Salgar']);
		Ciudad::create(['id' => '90', 'idDepartamento' => ' 2', 'nombre' => 'San Andrés de Cuerquía']);
		Ciudad::create(['id' => '91', 'idDepartamento' => ' 2', 'nombre' => 'San Carlos']);
		Ciudad::create(['id' => '92', 'idDepartamento' => ' 2', 'nombre' => 'San Francisco']);
		Ciudad::create(['id' => '93', 'idDepartamento' => ' 2', 'nombre' => 'San Jerónimo']);
		Ciudad::create(['id' => '94', 'idDepartamento' => ' 2', 'nombre' => 'San José de Montaña']);
		Ciudad::create(['id' => '95', 'idDepartamento' => ' 2', 'nombre' => 'San Juan de Urabá']);
		Ciudad::create(['id' => '96', 'idDepartamento' => ' 2', 'nombre' => 'San Luís']);
		Ciudad::create(['id' => '97', 'idDepartamento' => ' 2', 'nombre' => 'San Pedro']);
		Ciudad::create(['id' => '98', 'idDepartamento' => ' 2', 'nombre' => 'San Pedro de Urabá']);
		Ciudad::create(['id' => '99', 'idDepartamento' => ' 2', 'nombre' => 'San Rafael']);
		Ciudad::create(['id' => '100', 'idDepartamento' => ' 2', 'nombre' => 'San Roque']);
		Ciudad::create(['id' => '101', 'idDepartamento' => ' 2', 'nombre' => 'San Vicente']);
		Ciudad::create(['id' => '102', 'idDepartamento' => ' 2', 'nombre' => 'Santa Bárbara']);
		Ciudad::create(['id' => '103', 'idDepartamento' => ' 2', 'nombre' => 'Santa Fé de Antioquia']);
		Ciudad::create(['id' => '104', 'idDepartamento' => ' 2', 'nombre' => 'Santa Rosa de Osos']);
		Ciudad::create(['id' => '105', 'idDepartamento' => ' 2', 'nombre' => 'Santo Domingo']);
		Ciudad::create(['id' => '106', 'idDepartamento' => ' 2', 'nombre' => 'Santuario']);
		Ciudad::create(['id' => '107', 'idDepartamento' => ' 2', 'nombre' => 'Segovia']);
		Ciudad::create(['id' => '108', 'idDepartamento' => ' 2', 'nombre' => 'Sonsón']);
		Ciudad::create(['id' => '109', 'idDepartamento' => ' 2', 'nombre' => 'Sopetrán']);
		Ciudad::create(['id' => '110', 'idDepartamento' => ' 2', 'nombre' => 'Tarazá']);
		Ciudad::create(['id' => '111', 'idDepartamento' => ' 2', 'nombre' => 'Tarso']);
		Ciudad::create(['id' => '112', 'idDepartamento' => ' 2', 'nombre' => 'Titiribí']);
		Ciudad::create(['id' => '113', 'idDepartamento' => ' 2', 'nombre' => 'Toledo']);
		Ciudad::create(['id' => '114', 'idDepartamento' => ' 2', 'nombre' => 'Turbo']);
		Ciudad::create(['id' => '115', 'idDepartamento' => ' 2', 'nombre' => 'Támesis']);
		Ciudad::create(['id' => '116', 'idDepartamento' => ' 2', 'nombre' => 'Uramita']);
		Ciudad::create(['id' => '117', 'idDepartamento' => ' 2', 'nombre' => 'Urrao']);
		Ciudad::create(['id' => '118', 'idDepartamento' => ' 2', 'nombre' => 'Valdivia']);
		Ciudad::create(['id' => '119', 'idDepartamento' => ' 2', 'nombre' => 'Valparaiso']);
		Ciudad::create(['id' => '120', 'idDepartamento' => ' 2', 'nombre' => 'Vegachí']);
		Ciudad::create(['id' => '121', 'idDepartamento' => ' 2', 'nombre' => 'Venecia']);
		Ciudad::create(['id' => '122', 'idDepartamento' => ' 2', 'nombre' => 'Vigía del Fuerte']);
		Ciudad::create(['id' => '123', 'idDepartamento' => ' 2', 'nombre' => 'Yalí']);
		Ciudad::create(['id' => '124', 'idDepartamento' => ' 2', 'nombre' => 'Yarumal']);
		Ciudad::create(['id' => '125', 'idDepartamento' => ' 2', 'nombre' => 'Yolombó']);
		Ciudad::create(['id' => '126', 'idDepartamento' => ' 2', 'nombre' => 'Yondó (Casabe)']);
		Ciudad::create(['id' => '127', 'idDepartamento' => ' 2', 'nombre' => 'Zaragoza']);
		Ciudad::create(['id' => '128', 'idDepartamento' => ' 3', 'nombre' => 'Arauca']);
		Ciudad::create(['id' => '129', 'idDepartamento' => ' 3', 'nombre' => 'Arauquita']);
		Ciudad::create(['id' => '130', 'idDepartamento' => ' 3', 'nombre' => 'Cravo Norte']);
		Ciudad::create(['id' => '131', 'idDepartamento' => ' 3', 'nombre' => 'Fortúl']);
		Ciudad::create(['id' => '132', 'idDepartamento' => ' 3', 'nombre' => 'Puerto Rondón']);
		Ciudad::create(['id' => '133', 'idDepartamento' => ' 3', 'nombre' => 'Saravena']);
		Ciudad::create(['id' => '134', 'idDepartamento' => ' 3', 'nombre' => 'Tame']);
		Ciudad::create(['id' => '135', 'idDepartamento' => ' 4', 'nombre' => 'Baranoa']);
		Ciudad::create(['id' => '136', 'idDepartamento' => ' 4', 'nombre' => 'Barranquilla']);
		Ciudad::create(['id' => '137', 'idDepartamento' => ' 4', 'nombre' => 'Campo de la Cruz']);
		Ciudad::create(['id' => '138', 'idDepartamento' => ' 4', 'nombre' => 'Candelaria']);
		Ciudad::create(['id' => '139', 'idDepartamento' => ' 4', 'nombre' => 'Galapa']);
		Ciudad::create(['id' => '140', 'idDepartamento' => ' 4', 'nombre' => 'Juan de Acosta']);
		Ciudad::create(['id' => '141', 'idDepartamento' => ' 4', 'nombre' => 'Luruaco']);
		Ciudad::create(['id' => '142', 'idDepartamento' => ' 4', 'nombre' => 'Malambo']);
		Ciudad::create(['id' => '143', 'idDepartamento' => ' 4', 'nombre' => 'Manatí']);
		Ciudad::create(['id' => '144', 'idDepartamento' => ' 4', 'nombre' => 'Palmar de Varela']);
		Ciudad::create(['id' => '145', 'idDepartamento' => ' 4', 'nombre' => 'Piojo']);
		Ciudad::create(['id' => '146', 'idDepartamento' => ' 4', 'nombre' => 'Polonuevo']);
		Ciudad::create(['id' => '147', 'idDepartamento' => ' 4', 'nombre' => 'Ponedera']);
		Ciudad::create(['id' => '148', 'idDepartamento' => ' 4', 'nombre' => 'Puerto Colombia']);
		Ciudad::create(['id' => '149', 'idDepartamento' => ' 4', 'nombre' => 'Repelón']);
		Ciudad::create(['id' => '150', 'idDepartamento' => ' 4', 'nombre' => 'Sabanagrande']);
		Ciudad::create(['id' => '151', 'idDepartamento' => ' 4', 'nombre' => 'Sabanalarga']);
		Ciudad::create(['id' => '152', 'idDepartamento' => ' 4', 'nombre' => 'Santa Lucía']);
		Ciudad::create(['id' => '153', 'idDepartamento' => ' 4', 'nombre' => 'Santo Tomás']);
		Ciudad::create(['id' => '154', 'idDepartamento' => ' 4', 'nombre' => 'Soledad']);
		Ciudad::create(['id' => '155', 'idDepartamento' => ' 4', 'nombre' => 'Suan']);
		Ciudad::create(['id' => '156', 'idDepartamento' => ' 4', 'nombre' => 'Tubará']);
		Ciudad::create(['id' => '157', 'idDepartamento' => ' 4', 'nombre' => 'Usiacuri']);
		Ciudad::create(['id' => '158', 'idDepartamento' => ' 5', 'nombre' => 'Achí']);
		Ciudad::create(['id' => '159', 'idDepartamento' => ' 5', 'nombre' => 'Altos del Rosario']);
		Ciudad::create(['id' => '160', 'idDepartamento' => ' 5', 'nombre' => 'Arenal']);
		Ciudad::create(['id' => '161', 'idDepartamento' => ' 5', 'nombre' => 'Arjona']);
		Ciudad::create(['id' => '162', 'idDepartamento' => ' 5', 'nombre' => 'Arroyohondo']);
		Ciudad::create(['id' => '163', 'idDepartamento' => ' 5', 'nombre' => 'Barranco de Loba']);
		Ciudad::create(['id' => '164', 'idDepartamento' => ' 5', 'nombre' => 'Calamar']);
		Ciudad::create(['id' => '165', 'idDepartamento' => ' 5', 'nombre' => 'Cantagallo']);
		Ciudad::create(['id' => '166', 'idDepartamento' => ' 5', 'nombre' => 'Cartagena']);
		Ciudad::create(['id' => '167', 'idDepartamento' => ' 5', 'nombre' => 'Cicuco']);
		Ciudad::create(['id' => '168', 'idDepartamento' => ' 5', 'nombre' => 'Clemencia']);
		Ciudad::create(['id' => '169', 'idDepartamento' => ' 5', 'nombre' => 'Córdoba']);
		Ciudad::create(['id' => '170', 'idDepartamento' => ' 5', 'nombre' => 'El Carmen de Bolívar']);
		Ciudad::create(['id' => '171', 'idDepartamento' => ' 5', 'nombre' => 'El Guamo']);
		Ciudad::create(['id' => '172', 'idDepartamento' => ' 5', 'nombre' => 'El Peñon']);
		Ciudad::create(['id' => '173', 'idDepartamento' => ' 5', 'nombre' => 'Hatillo de Loba']);
		Ciudad::create(['id' => '174', 'idDepartamento' => ' 5', 'nombre' => 'Magangué']);
		Ciudad::create(['id' => '175', 'idDepartamento' => ' 5', 'nombre' => 'Mahates']);
		Ciudad::create(['id' => '176', 'idDepartamento' => ' 5', 'nombre' => 'Margarita']);
		Ciudad::create(['id' => '177', 'idDepartamento' => ' 5', 'nombre' => 'María la Baja']);
		Ciudad::create(['id' => '178', 'idDepartamento' => ' 5', 'nombre' => 'Mompós']);
		Ciudad::create(['id' => '179', 'idDepartamento' => ' 5', 'nombre' => 'Montecristo']);
		Ciudad::create(['id' => '180', 'idDepartamento' => ' 5', 'nombre' => 'Morales']);
		Ciudad::create(['id' => '181', 'idDepartamento' => ' 5', 'nombre' => 'Norosí']);
		Ciudad::create(['id' => '182', 'idDepartamento' => ' 5', 'nombre' => 'Pinillos']);
		Ciudad::create(['id' => '183', 'idDepartamento' => ' 5', 'nombre' => 'Regidor']);
		Ciudad::create(['id' => '184', 'idDepartamento' => ' 5', 'nombre' => 'Río Viejo']);
		Ciudad::create(['id' => '185', 'idDepartamento' => ' 5', 'nombre' => 'San Cristobal']);
		Ciudad::create(['id' => '186', 'idDepartamento' => ' 5', 'nombre' => 'San Estanislao']);
		Ciudad::create(['id' => '187', 'idDepartamento' => ' 5', 'nombre' => 'San Fernando']);
		Ciudad::create(['id' => '188', 'idDepartamento' => ' 5', 'nombre' => 'San Jacinto']);
		Ciudad::create(['id' => '189', 'idDepartamento' => ' 5', 'nombre' => 'San Jacinto del Cauca']);
		Ciudad::create(['id' => '190', 'idDepartamento' => ' 5', 'nombre' => 'San Juan de Nepomuceno']);
		Ciudad::create(['id' => '191', 'idDepartamento' => ' 5', 'nombre' => 'San Martín de Loba']);
		Ciudad::create(['id' => '192', 'idDepartamento' => ' 5', 'nombre' => 'San Pablo']);
		Ciudad::create(['id' => '193', 'idDepartamento' => ' 5', 'nombre' => 'Santa Catalina']);
		Ciudad::create(['id' => '194', 'idDepartamento' => ' 5', 'nombre' => 'Santa Rosa ']);
		Ciudad::create(['id' => '195', 'idDepartamento' => ' 5', 'nombre' => 'Santa Rosa del Sur']);
		Ciudad::create(['id' => '196', 'idDepartamento' => ' 5', 'nombre' => 'Simití']);
		Ciudad::create(['id' => '197', 'idDepartamento' => ' 5', 'nombre' => 'Soplaviento']);
		Ciudad::create(['id' => '198', 'idDepartamento' => ' 5', 'nombre' => 'Talaigua Nuevo']);
		Ciudad::create(['id' => '199', 'idDepartamento' => ' 5', 'nombre' => 'Tiquisio (Puerto Rico)']);
		Ciudad::create(['id' => '200', 'idDepartamento' => ' 5', 'nombre' => 'Turbaco']);
		Ciudad::create(['id' => '201', 'idDepartamento' => ' 5', 'nombre' => 'Turbaná']);
		Ciudad::create(['id' => '202', 'idDepartamento' => ' 5', 'nombre' => 'Villanueva']);
		Ciudad::create(['id' => '203', 'idDepartamento' => ' 5', 'nombre' => 'Zambrano']);
		Ciudad::create(['id' => '204', 'idDepartamento' => ' 6', 'nombre' => 'Almeida']);
		Ciudad::create(['id' => '205', 'idDepartamento' => ' 6', 'nombre' => 'Aquitania']);
		Ciudad::create(['id' => '206', 'idDepartamento' => ' 6', 'nombre' => 'Arcabuco']);
		Ciudad::create(['id' => '207', 'idDepartamento' => ' 6', 'nombre' => 'Belén']);
		Ciudad::create(['id' => '208', 'idDepartamento' => ' 6', 'nombre' => 'Berbeo']);
		Ciudad::create(['id' => '209', 'idDepartamento' => ' 6', 'nombre' => 'Beteitiva']);
		Ciudad::create(['id' => '210', 'idDepartamento' => ' 6', 'nombre' => 'Boavita']);
		Ciudad::create(['id' => '211', 'idDepartamento' => ' 6', 'nombre' => 'Boyacá']);
		Ciudad::create(['id' => '212', 'idDepartamento' => ' 6', 'nombre' => 'Briceño']);
		Ciudad::create(['id' => '213', 'idDepartamento' => ' 6', 'nombre' => 'Buenavista']);
		Ciudad::create(['id' => '214', 'idDepartamento' => ' 6', 'nombre' => 'Busbanza']);
		Ciudad::create(['id' => '215', 'idDepartamento' => ' 6', 'nombre' => 'Caldas']);
		Ciudad::create(['id' => '216', 'idDepartamento' => ' 6', 'nombre' => 'Campohermoso']);
		Ciudad::create(['id' => '217', 'idDepartamento' => ' 6', 'nombre' => 'Cerinza']);
		Ciudad::create(['id' => '218', 'idDepartamento' => ' 6', 'nombre' => 'Chinavita']);
		Ciudad::create(['id' => '219', 'idDepartamento' => ' 6', 'nombre' => 'Chiquinquirá']);
		Ciudad::create(['id' => '220', 'idDepartamento' => ' 6', 'nombre' => 'Chiscas']);
		Ciudad::create(['id' => '221', 'idDepartamento' => ' 6', 'nombre' => 'Chita']);
		Ciudad::create(['id' => '222', 'idDepartamento' => ' 6', 'nombre' => 'Chitaraque']);
		Ciudad::create(['id' => '223', 'idDepartamento' => ' 6', 'nombre' => 'Chivatá']);
		Ciudad::create(['id' => '224', 'idDepartamento' => ' 6', 'nombre' => 'Chíquiza']);
		Ciudad::create(['id' => '225', 'idDepartamento' => ' 6', 'nombre' => 'Chívor']);
		Ciudad::create(['id' => '226', 'idDepartamento' => ' 6', 'nombre' => 'Ciénaga']);
		Ciudad::create(['id' => '227', 'idDepartamento' => ' 6', 'nombre' => 'Coper']);
		Ciudad::create(['id' => '228', 'idDepartamento' => ' 6', 'nombre' => 'Corrales']);
		Ciudad::create(['id' => '229', 'idDepartamento' => ' 6', 'nombre' => 'Covarachía']);
		Ciudad::create(['id' => '230', 'idDepartamento' => ' 6', 'nombre' => 'Cubará']);
		Ciudad::create(['id' => '231', 'idDepartamento' => ' 6', 'nombre' => 'Cucaita']);
		Ciudad::create(['id' => '232', 'idDepartamento' => ' 6', 'nombre' => 'Cuitiva']);
		Ciudad::create(['id' => '233', 'idDepartamento' => ' 6', 'nombre' => 'Cómbita']);
		Ciudad::create(['id' => '234', 'idDepartamento' => ' 6', 'nombre' => 'Duitama']);
		Ciudad::create(['id' => '235', 'idDepartamento' => ' 6', 'nombre' => 'El Cocuy']);
		Ciudad::create(['id' => '236', 'idDepartamento' => ' 6', 'nombre' => 'El Espino']);
		Ciudad::create(['id' => '237', 'idDepartamento' => ' 6', 'nombre' => 'Firavitoba']);
		Ciudad::create(['id' => '238', 'idDepartamento' => ' 6', 'nombre' => 'Floresta']);
		Ciudad::create(['id' => '239', 'idDepartamento' => ' 6', 'nombre' => 'Gachantivá']);
		Ciudad::create(['id' => '240', 'idDepartamento' => ' 6', 'nombre' => 'Garagoa']);
		Ciudad::create(['id' => '241', 'idDepartamento' => ' 6', 'nombre' => 'Guacamayas']);
		Ciudad::create(['id' => '242', 'idDepartamento' => ' 6', 'nombre' => 'Guateque']);
		Ciudad::create(['id' => '243', 'idDepartamento' => ' 6', 'nombre' => 'Guayatá']);
		Ciudad::create(['id' => '244', 'idDepartamento' => ' 6', 'nombre' => 'Guicán']);
		Ciudad::create(['id' => '245', 'idDepartamento' => ' 6', 'nombre' => 'Gámeza']);
		Ciudad::create(['id' => '246', 'idDepartamento' => ' 6', 'nombre' => 'Izá']);
		Ciudad::create(['id' => '247', 'idDepartamento' => ' 6', 'nombre' => 'Jenesano']);
		Ciudad::create(['id' => '248', 'idDepartamento' => ' 6', 'nombre' => 'Jericó']);
		Ciudad::create(['id' => '249', 'idDepartamento' => ' 6', 'nombre' => 'La Capilla']);
		Ciudad::create(['id' => '250', 'idDepartamento' => ' 6', 'nombre' => 'La Uvita']);
		Ciudad::create(['id' => '251', 'idDepartamento' => ' 6', 'nombre' => 'La Victoria']);
		Ciudad::create(['id' => '252', 'idDepartamento' => ' 6', 'nombre' => 'Labranzagrande']);
		Ciudad::create(['id' => '253', 'idDepartamento' => ' 6', 'nombre' => 'Macanal']);
		Ciudad::create(['id' => '254', 'idDepartamento' => ' 6', 'nombre' => 'Maripí']);
		Ciudad::create(['id' => '255', 'idDepartamento' => ' 6', 'nombre' => 'Miraflores']);
		Ciudad::create(['id' => '256', 'idDepartamento' => ' 6', 'nombre' => 'Mongua']);
		Ciudad::create(['id' => '257', 'idDepartamento' => ' 6', 'nombre' => 'Monguí']);
		Ciudad::create(['id' => '258', 'idDepartamento' => ' 6', 'nombre' => 'Moniquirá']);
		Ciudad::create(['id' => '259', 'idDepartamento' => ' 6', 'nombre' => 'Motavita']);
		Ciudad::create(['id' => '260', 'idDepartamento' => ' 6', 'nombre' => 'Muzo']);
		Ciudad::create(['id' => '261', 'idDepartamento' => ' 6', 'nombre' => 'Nobsa']);
		Ciudad::create(['id' => '262', 'idDepartamento' => ' 6', 'nombre' => 'Nuevo Colón']);
		Ciudad::create(['id' => '263', 'idDepartamento' => ' 6', 'nombre' => 'Oicatá']);
		Ciudad::create(['id' => '264', 'idDepartamento' => ' 6', 'nombre' => 'Otanche']);
		Ciudad::create(['id' => '265', 'idDepartamento' => ' 6', 'nombre' => 'Pachavita']);
		Ciudad::create(['id' => '266', 'idDepartamento' => ' 6', 'nombre' => 'Paipa']);
		Ciudad::create(['id' => '267', 'idDepartamento' => ' 6', 'nombre' => 'Pajarito']);
		Ciudad::create(['id' => '268', 'idDepartamento' => ' 6', 'nombre' => 'Panqueba']);
		Ciudad::create(['id' => '269', 'idDepartamento' => ' 6', 'nombre' => 'Pauna']);
		Ciudad::create(['id' => '270', 'idDepartamento' => ' 6', 'nombre' => 'Paya']);
		Ciudad::create(['id' => '271', 'idDepartamento' => ' 6', 'nombre' => 'Paz de Río']);
		Ciudad::create(['id' => '272', 'idDepartamento' => ' 6', 'nombre' => 'Pesca']);
		Ciudad::create(['id' => '273', 'idDepartamento' => ' 6', 'nombre' => 'Pisva']);
		Ciudad::create(['id' => '274', 'idDepartamento' => ' 6', 'nombre' => 'Puerto Boyacá']);
		Ciudad::create(['id' => '275', 'idDepartamento' => ' 6', 'nombre' => 'Páez']);
		Ciudad::create(['id' => '276', 'idDepartamento' => ' 6', 'nombre' => 'Quipama']);
		Ciudad::create(['id' => '277', 'idDepartamento' => ' 6', 'nombre' => 'Ramiriquí']);
		Ciudad::create(['id' => '278', 'idDepartamento' => ' 6', 'nombre' => 'Rondón']);
		Ciudad::create(['id' => '279', 'idDepartamento' => ' 6', 'nombre' => 'Ráquira']);
		Ciudad::create(['id' => '280', 'idDepartamento' => ' 6', 'nombre' => 'Saboyá']);
		Ciudad::create(['id' => '281', 'idDepartamento' => ' 6', 'nombre' => 'Samacá']);
		Ciudad::create(['id' => '282', 'idDepartamento' => ' 6', 'nombre' => 'San Eduardo']);
		Ciudad::create(['id' => '283', 'idDepartamento' => ' 6', 'nombre' => 'San José de Pare']);
		Ciudad::create(['id' => '284', 'idDepartamento' => ' 6', 'nombre' => 'San Luís de Gaceno']);
		Ciudad::create(['id' => '285', 'idDepartamento' => ' 6', 'nombre' => 'San Mateo']);
		Ciudad::create(['id' => '286', 'idDepartamento' => ' 6', 'nombre' => 'San Miguel de Sema']);
		Ciudad::create(['id' => '287', 'idDepartamento' => ' 6', 'nombre' => 'San Pablo de Borbur']);
		Ciudad::create(['id' => '288', 'idDepartamento' => ' 6', 'nombre' => 'Santa María']);
		Ciudad::create(['id' => '289', 'idDepartamento' => ' 6', 'nombre' => 'Santa Rosa de Viterbo']);
		Ciudad::create(['id' => '290', 'idDepartamento' => ' 6', 'nombre' => 'Santa Sofía']);
		Ciudad::create(['id' => '291', 'idDepartamento' => ' 6', 'nombre' => 'Santana']);
		Ciudad::create(['id' => '292', 'idDepartamento' => ' 6', 'nombre' => 'Sativanorte']);
		Ciudad::create(['id' => '293', 'idDepartamento' => ' 6', 'nombre' => 'Sativasur']);
		Ciudad::create(['id' => '294', 'idDepartamento' => ' 6', 'nombre' => 'Siachoque']);
		Ciudad::create(['id' => '295', 'idDepartamento' => ' 6', 'nombre' => 'Soatá']);
		Ciudad::create(['id' => '296', 'idDepartamento' => ' 6', 'nombre' => 'Socha']);
		Ciudad::create(['id' => '297', 'idDepartamento' => ' 6', 'nombre' => 'Socotá']);
		Ciudad::create(['id' => '298', 'idDepartamento' => ' 6', 'nombre' => 'Sogamoso']);
		Ciudad::create(['id' => '299', 'idDepartamento' => ' 6', 'nombre' => 'Somondoco']);
		Ciudad::create(['id' => '300', 'idDepartamento' => ' 6', 'nombre' => 'Sora']);
		Ciudad::create(['id' => '301', 'idDepartamento' => ' 6', 'nombre' => 'Soracá']);
		Ciudad::create(['id' => '302', 'idDepartamento' => ' 6', 'nombre' => 'Sotaquirá']);
		Ciudad::create(['id' => '303', 'idDepartamento' => ' 6', 'nombre' => 'Susacón']);
		Ciudad::create(['id' => '304', 'idDepartamento' => ' 6', 'nombre' => 'Sutamarchán']);
		Ciudad::create(['id' => '305', 'idDepartamento' => ' 6', 'nombre' => 'Sutatenza']);
		Ciudad::create(['id' => '306', 'idDepartamento' => ' 6', 'nombre' => 'Sáchica']);
		Ciudad::create(['id' => '307', 'idDepartamento' => ' 6', 'nombre' => 'Tasco']);
		Ciudad::create(['id' => '308', 'idDepartamento' => ' 6', 'nombre' => 'Tenza']);
		Ciudad::create(['id' => '309', 'idDepartamento' => ' 6', 'nombre' => 'Tibaná']);
		Ciudad::create(['id' => '310', 'idDepartamento' => ' 6', 'nombre' => 'Tibasosa']);
		Ciudad::create(['id' => '311', 'idDepartamento' => ' 6', 'nombre' => 'Tinjacá']);
		Ciudad::create(['id' => '312', 'idDepartamento' => ' 6', 'nombre' => 'Tipacoque']);
		Ciudad::create(['id' => '313', 'idDepartamento' => ' 6', 'nombre' => 'Toca']);
		Ciudad::create(['id' => '314', 'idDepartamento' => ' 6', 'nombre' => 'Toguí']);
		Ciudad::create(['id' => '315', 'idDepartamento' => ' 6', 'nombre' => 'Topagá']);
		Ciudad::create(['id' => '316', 'idDepartamento' => ' 6', 'nombre' => 'Tota']);
		Ciudad::create(['id' => '317', 'idDepartamento' => ' 6', 'nombre' => 'Tunja']);
		Ciudad::create(['id' => '318', 'idDepartamento' => ' 6', 'nombre' => 'Tunungua']);
		Ciudad::create(['id' => '319', 'idDepartamento' => ' 6', 'nombre' => 'Turmequé']);
		Ciudad::create(['id' => '320', 'idDepartamento' => ' 6', 'nombre' => 'Tuta']);
		Ciudad::create(['id' => '321', 'idDepartamento' => ' 6', 'nombre' => 'Tutasá']);
		Ciudad::create(['id' => '322', 'idDepartamento' => ' 6', 'nombre' => 'Ventaquemada']);
		Ciudad::create(['id' => '323', 'idDepartamento' => ' 6', 'nombre' => 'Villa de Leiva']);
		Ciudad::create(['id' => '324', 'idDepartamento' => ' 6', 'nombre' => 'Viracachá']);
		Ciudad::create(['id' => '325', 'idDepartamento' => ' 6', 'nombre' => 'Zetaquirá']);
		Ciudad::create(['id' => '326', 'idDepartamento' => ' 6', 'nombre' => 'Úmbita']);
		Ciudad::create(['id' => '327', 'idDepartamento' => ' 7', 'nombre' => 'Aguadas']);
		Ciudad::create(['id' => '328', 'idDepartamento' => ' 7', 'nombre' => 'Anserma']);
		Ciudad::create(['id' => '329', 'idDepartamento' => ' 7', 'nombre' => 'Aranzazu']);
		Ciudad::create(['id' => '330', 'idDepartamento' => ' 7', 'nombre' => 'Belalcázar']);
		Ciudad::create(['id' => '331', 'idDepartamento' => ' 7', 'nombre' => 'Chinchiná']);
		Ciudad::create(['id' => '332', 'idDepartamento' => ' 7', 'nombre' => 'Filadelfia']);
		Ciudad::create(['id' => '333', 'idDepartamento' => ' 7', 'nombre' => 'La Dorada']);
		Ciudad::create(['id' => '334', 'idDepartamento' => ' 7', 'nombre' => 'La Merced']);
		Ciudad::create(['id' => '335', 'idDepartamento' => ' 7', 'nombre' => 'La Victoria']);
		Ciudad::create(['id' => '336', 'idDepartamento' => ' 7', 'nombre' => 'Manizales']);
		Ciudad::create(['id' => '337', 'idDepartamento' => ' 7', 'nombre' => 'Manzanares']);
		Ciudad::create(['id' => '338', 'idDepartamento' => ' 7', 'nombre' => 'Marmato']);
		Ciudad::create(['id' => '339', 'idDepartamento' => ' 7', 'nombre' => 'Marquetalia']);
		Ciudad::create(['id' => '340', 'idDepartamento' => ' 7', 'nombre' => 'Marulanda']);
		Ciudad::create(['id' => '341', 'idDepartamento' => ' 7', 'nombre' => 'Neira']);
		Ciudad::create(['id' => '342', 'idDepartamento' => ' 7', 'nombre' => 'Norcasia']);
		Ciudad::create(['id' => '343', 'idDepartamento' => ' 7', 'nombre' => 'Palestina']);
		Ciudad::create(['id' => '344', 'idDepartamento' => ' 7', 'nombre' => 'Pensilvania']);
		Ciudad::create(['id' => '345', 'idDepartamento' => ' 7', 'nombre' => 'Pácora']);
		Ciudad::create(['id' => '346', 'idDepartamento' => ' 7', 'nombre' => 'Risaralda']);
		Ciudad::create(['id' => '347', 'idDepartamento' => ' 7', 'nombre' => 'Río Sucio']);
		Ciudad::create(['id' => '348', 'idDepartamento' => ' 7', 'nombre' => 'Salamina']);
		Ciudad::create(['id' => '349', 'idDepartamento' => ' 7', 'nombre' => 'Samaná']);
		Ciudad::create(['id' => '350', 'idDepartamento' => ' 7', 'nombre' => 'San José']);
		Ciudad::create(['id' => '351', 'idDepartamento' => ' 7', 'nombre' => 'Supía']);
		Ciudad::create(['id' => '352', 'idDepartamento' => ' 7', 'nombre' => 'Villamaría']);
		Ciudad::create(['id' => '353', 'idDepartamento' => ' 7', 'nombre' => 'Viterbo']);
		Ciudad::create(['id' => '354', 'idDepartamento' => ' 8', 'nombre' => 'Albania']);
		Ciudad::create(['id' => '355', 'idDepartamento' => ' 8', 'nombre' => 'Belén de los Andaquíes']);
		Ciudad::create(['id' => '356', 'idDepartamento' => ' 8', 'nombre' => 'Cartagena del Chairá']);
		Ciudad::create(['id' => '357', 'idDepartamento' => ' 8', 'nombre' => 'Curillo']);
		Ciudad::create(['id' => '358', 'idDepartamento' => ' 8', 'nombre' => 'El Doncello']);
		Ciudad::create(['id' => '359', 'idDepartamento' => ' 8', 'nombre' => 'El Paujil']);
		Ciudad::create(['id' => '360', 'idDepartamento' => ' 8', 'nombre' => 'Florencia']);
		Ciudad::create(['id' => '361', 'idDepartamento' => ' 8', 'nombre' => 'La Montañita']);
		Ciudad::create(['id' => '362', 'idDepartamento' => ' 8', 'nombre' => 'Milán']);
		Ciudad::create(['id' => '363', 'idDepartamento' => ' 8', 'nombre' => 'Morelia']);
		Ciudad::create(['id' => '364', 'idDepartamento' => ' 8', 'nombre' => 'Puerto Rico']);
		Ciudad::create(['id' => '365', 'idDepartamento' => ' 8', 'nombre' => 'San José del Fragua']);
		Ciudad::create(['id' => '366', 'idDepartamento' => ' 8', 'nombre' => 'San Vicente del Caguán']);
		Ciudad::create(['id' => '367', 'idDepartamento' => ' 8', 'nombre' => 'Solano']);
		Ciudad::create(['id' => '368', 'idDepartamento' => ' 8', 'nombre' => 'Solita']);
		Ciudad::create(['id' => '369', 'idDepartamento' => ' 8', 'nombre' => 'Valparaiso']);
		Ciudad::create(['id' => '370', 'idDepartamento' => ' 9', 'nombre' => 'Aguazul']);
		Ciudad::create(['id' => '371', 'idDepartamento' => ' 9', 'nombre' => 'Chámeza']);
		Ciudad::create(['id' => '372', 'idDepartamento' => ' 9', 'nombre' => 'Hato Corozal']);
		Ciudad::create(['id' => '373', 'idDepartamento' => ' 9', 'nombre' => 'La Salina']);
		Ciudad::create(['id' => '374', 'idDepartamento' => ' 9', 'nombre' => 'Maní']);
		Ciudad::create(['id' => '375', 'idDepartamento' => ' 9', 'nombre' => 'Monterrey']);
		Ciudad::create(['id' => '376', 'idDepartamento' => ' 9', 'nombre' => 'Nunchía']);
		Ciudad::create(['id' => '377', 'idDepartamento' => ' 9', 'nombre' => 'Orocué']);
		Ciudad::create(['id' => '378', 'idDepartamento' => ' 9', 'nombre' => 'Paz de Ariporo']);
		Ciudad::create(['id' => '379', 'idDepartamento' => ' 9', 'nombre' => 'Pore']);
		Ciudad::create(['id' => '380', 'idDepartamento' => ' 9', 'nombre' => 'Recetor']);
		Ciudad::create(['id' => '381', 'idDepartamento' => ' 9', 'nombre' => 'Sabanalarga']);
		Ciudad::create(['id' => '382', 'idDepartamento' => ' 9', 'nombre' => 'San Luís de Palenque']);
		Ciudad::create(['id' => '383', 'idDepartamento' => ' 9', 'nombre' => 'Sácama']);
		Ciudad::create(['id' => '384', 'idDepartamento' => ' 9', 'nombre' => 'Tauramena']);
		Ciudad::create(['id' => '385', 'idDepartamento' => ' 9', 'nombre' => 'Trinidad']);
		Ciudad::create(['id' => '386', 'idDepartamento' => ' 9', 'nombre' => 'Támara']);
		Ciudad::create(['id' => '387', 'idDepartamento' => ' 9', 'nombre' => 'Villanueva']);
		Ciudad::create(['id' => '388', 'idDepartamento' => ' 9', 'nombre' => 'Yopal']);
		Ciudad::create(['id' => '389', 'idDepartamento' => ' 10', 'nombre' => 'Almaguer']);
		Ciudad::create(['id' => '390', 'idDepartamento' => ' 10', 'nombre' => 'Argelia']);
		Ciudad::create(['id' => '391', 'idDepartamento' => ' 10', 'nombre' => 'Balboa']);
		Ciudad::create(['id' => '392', 'idDepartamento' => ' 10', 'nombre' => 'Bolívar']);
		Ciudad::create(['id' => '393', 'idDepartamento' => ' 10', 'nombre' => 'Buenos Aires']);
		Ciudad::create(['id' => '394', 'idDepartamento' => ' 10', 'nombre' => 'Cajibío']);
		Ciudad::create(['id' => '395', 'idDepartamento' => ' 10', 'nombre' => 'Caldono']);
		Ciudad::create(['id' => '396', 'idDepartamento' => ' 10', 'nombre' => 'Caloto']);
		Ciudad::create(['id' => '397', 'idDepartamento' => ' 10', 'nombre' => 'Corinto']);
		Ciudad::create(['id' => '398', 'idDepartamento' => ' 10', 'nombre' => 'El Tambo']);
		Ciudad::create(['id' => '399', 'idDepartamento' => ' 10', 'nombre' => 'Florencia']);
		Ciudad::create(['id' => '400', 'idDepartamento' => ' 10', 'nombre' => 'Guachené']);
		Ciudad::create(['id' => '401', 'idDepartamento' => ' 10', 'nombre' => 'Guapí']);
		Ciudad::create(['id' => '402', 'idDepartamento' => ' 10', 'nombre' => 'Inzá']);
		Ciudad::create(['id' => '403', 'idDepartamento' => ' 10', 'nombre' => 'Jambaló']);
		Ciudad::create(['id' => '404', 'idDepartamento' => ' 10', 'nombre' => 'La Sierra']);
		Ciudad::create(['id' => '405', 'idDepartamento' => ' 10', 'nombre' => 'La Vega']);
		Ciudad::create(['id' => '406', 'idDepartamento' => ' 10', 'nombre' => 'López (Micay)']);
		Ciudad::create(['id' => '407', 'idDepartamento' => ' 10', 'nombre' => 'Mercaderes']);
		Ciudad::create(['id' => '408', 'idDepartamento' => ' 10', 'nombre' => 'Miranda']);
		Ciudad::create(['id' => '409', 'idDepartamento' => ' 10', 'nombre' => 'Morales']);
		Ciudad::create(['id' => '410', 'idDepartamento' => ' 10', 'nombre' => 'Padilla']);
		Ciudad::create(['id' => '411', 'idDepartamento' => ' 10', 'nombre' => 'Patía (El Bordo)']);
		Ciudad::create(['id' => '412', 'idDepartamento' => ' 10', 'nombre' => 'Piamonte']);
		Ciudad::create(['id' => '413', 'idDepartamento' => ' 10', 'nombre' => 'Piendamó']);
		Ciudad::create(['id' => '414', 'idDepartamento' => ' 10', 'nombre' => 'Popayán']);
		Ciudad::create(['id' => '415', 'idDepartamento' => ' 10', 'nombre' => 'Puerto Tejada']);
		Ciudad::create(['id' => '416', 'idDepartamento' => ' 10', 'nombre' => 'Puracé (Coconuco)']);
		Ciudad::create(['id' => '417', 'idDepartamento' => ' 10', 'nombre' => 'Páez (Belalcazar)']);
		Ciudad::create(['id' => '418', 'idDepartamento' => ' 10', 'nombre' => 'Rosas']);
		Ciudad::create(['id' => '419', 'idDepartamento' => ' 10', 'nombre' => 'San Sebastián']);
		Ciudad::create(['id' => '420', 'idDepartamento' => ' 10', 'nombre' => 'Santa Rosa']);
		Ciudad::create(['id' => '421', 'idDepartamento' => ' 10', 'nombre' => 'Santander de Quilichao']);
		Ciudad::create(['id' => '422', 'idDepartamento' => ' 10', 'nombre' => 'Silvia']);
		Ciudad::create(['id' => '423', 'idDepartamento' => ' 10', 'nombre' => 'Sotara (Paispamba)']);
		Ciudad::create(['id' => '424', 'idDepartamento' => ' 10', 'nombre' => 'Sucre']);
		Ciudad::create(['id' => '425', 'idDepartamento' => ' 10', 'nombre' => 'Suárez']);
		Ciudad::create(['id' => '426', 'idDepartamento' => ' 10', 'nombre' => 'Timbiquí']);
		Ciudad::create(['id' => '427', 'idDepartamento' => ' 10', 'nombre' => 'Timbío']);
		Ciudad::create(['id' => '428', 'idDepartamento' => ' 10', 'nombre' => 'Toribío']);
		Ciudad::create(['id' => '429', 'idDepartamento' => ' 10', 'nombre' => 'Totoró']);
		Ciudad::create(['id' => '430', 'idDepartamento' => ' 10', 'nombre' => 'Villa Rica']);
		Ciudad::create(['id' => '431', 'idDepartamento' => ' 11', 'nombre' => 'Aguachica']);
		Ciudad::create(['id' => '432', 'idDepartamento' => ' 11', 'nombre' => 'Agustín Codazzi']);
		Ciudad::create(['id' => '433', 'idDepartamento' => ' 11', 'nombre' => 'Astrea']);
		Ciudad::create(['id' => '434', 'idDepartamento' => ' 11', 'nombre' => 'Becerríl']);
		Ciudad::create(['id' => '435', 'idDepartamento' => ' 11', 'nombre' => 'Bosconia']);
		Ciudad::create(['id' => '436', 'idDepartamento' => ' 11', 'nombre' => 'Chimichagua']);
		Ciudad::create(['id' => '437', 'idDepartamento' => ' 11', 'nombre' => 'Chiriguaná']);
		Ciudad::create(['id' => '438', 'idDepartamento' => ' 11', 'nombre' => 'Curumaní']);
		Ciudad::create(['id' => '439', 'idDepartamento' => ' 11', 'nombre' => 'El Copey']);
		Ciudad::create(['id' => '440', 'idDepartamento' => ' 11', 'nombre' => 'El Paso']);
		Ciudad::create(['id' => '441', 'idDepartamento' => ' 11', 'nombre' => 'Gamarra']);
		Ciudad::create(['id' => '442', 'idDepartamento' => ' 11', 'nombre' => 'Gonzalez']);
		Ciudad::create(['id' => '443', 'idDepartamento' => ' 11', 'nombre' => 'La Gloria']);
		Ciudad::create(['id' => '444', 'idDepartamento' => ' 11', 'nombre' => 'La Jagua de Ibirico']);
		Ciudad::create(['id' => '445', 'idDepartamento' => ' 11', 'nombre' => 'La Paz (Robles)']);
		Ciudad::create(['id' => '446', 'idDepartamento' => ' 11', 'nombre' => 'Manaure Balcón del Cesar']);
		Ciudad::create(['id' => '447', 'idDepartamento' => ' 11', 'nombre' => 'Pailitas']);
		Ciudad::create(['id' => '448', 'idDepartamento' => ' 11', 'nombre' => 'Pelaya']);
		Ciudad::create(['id' => '449', 'idDepartamento' => ' 11', 'nombre' => 'Pueblo Bello']);
		Ciudad::create(['id' => '450', 'idDepartamento' => ' 11', 'nombre' => 'Río de oro']);
		Ciudad::create(['id' => '451', 'idDepartamento' => ' 11', 'nombre' => 'San Alberto']);
		Ciudad::create(['id' => '452', 'idDepartamento' => ' 11', 'nombre' => 'San Diego']);
		Ciudad::create(['id' => '453', 'idDepartamento' => ' 11', 'nombre' => 'San Martín']);
		Ciudad::create(['id' => '454', 'idDepartamento' => ' 11', 'nombre' => 'Tamalameque']);
		Ciudad::create(['id' => '455', 'idDepartamento' => ' 11', 'nombre' => 'Valledupar']);
		Ciudad::create(['id' => '456', 'idDepartamento' => ' 12', 'nombre' => 'Acandí']);
		Ciudad::create(['id' => '457', 'idDepartamento' => ' 12', 'nombre' => 'Alto Baudó (Pie de Pato)']);
		Ciudad::create(['id' => '458', 'idDepartamento' => ' 12', 'nombre' => 'Atrato (Yuto)']);
		Ciudad::create(['id' => '459', 'idDepartamento' => ' 12', 'nombre' => 'Bagadó']);
		Ciudad::create(['id' => '460', 'idDepartamento' => ' 12', 'nombre' => 'Bahía Solano (Mútis)']);
		Ciudad::create(['id' => '461', 'idDepartamento' => ' 12', 'nombre' => 'Bajo Baudó (Pizarro)']);
		Ciudad::create(['id' => '462', 'idDepartamento' => ' 12', 'nombre' => 'Belén de Bajirá']);
		Ciudad::create(['id' => '463', 'idDepartamento' => ' 12', 'nombre' => 'Bojayá (Bellavista)']);
		Ciudad::create(['id' => '464', 'idDepartamento' => ' 12', 'nombre' => 'Cantón de San Pablo']);
		Ciudad::create(['id' => '465', 'idDepartamento' => ' 12', 'nombre' => 'Carmen del Darién (CURBARADÓ)']);
		Ciudad::create(['id' => '466', 'idDepartamento' => ' 12', 'nombre' => 'Condoto']);
		Ciudad::create(['id' => '467', 'idDepartamento' => ' 12', 'nombre' => 'Cértegui']);
		Ciudad::create(['id' => '468', 'idDepartamento' => ' 12', 'nombre' => 'El Carmen de Atrato']);
		Ciudad::create(['id' => '469', 'idDepartamento' => ' 12', 'nombre' => 'Istmina']);
		Ciudad::create(['id' => '470', 'idDepartamento' => ' 12', 'nombre' => 'Juradó']);
		Ciudad::create(['id' => '471', 'idDepartamento' => ' 12', 'nombre' => 'Lloró']);
		Ciudad::create(['id' => '472', 'idDepartamento' => ' 12', 'nombre' => 'Medio Atrato']);
		Ciudad::create(['id' => '473', 'idDepartamento' => ' 12', 'nombre' => 'Medio Baudó']);
		Ciudad::create(['id' => '474', 'idDepartamento' => ' 12', 'nombre' => 'Medio San Juan (ANDAGOYA)']);
		Ciudad::create(['id' => '475', 'idDepartamento' => ' 12', 'nombre' => 'Novita']);
		Ciudad::create(['id' => '476', 'idDepartamento' => ' 12', 'nombre' => 'Nuquí']);
		Ciudad::create(['id' => '477', 'idDepartamento' => ' 12', 'nombre' => 'Quibdó']);
		Ciudad::create(['id' => '478', 'idDepartamento' => ' 12', 'nombre' => 'Río Iró']);
		Ciudad::create(['id' => '479', 'idDepartamento' => ' 12', 'nombre' => 'Río Quito']);
		Ciudad::create(['id' => '480', 'idDepartamento' => ' 12', 'nombre' => 'Ríosucio']);
		Ciudad::create(['id' => '481', 'idDepartamento' => ' 12', 'nombre' => 'San José del Palmar']);
		Ciudad::create(['id' => '482', 'idDepartamento' => ' 12', 'nombre' => 'Santa Genoveva de Docorodó']);
		Ciudad::create(['id' => '483', 'idDepartamento' => ' 12', 'nombre' => 'Sipí']);
		Ciudad::create(['id' => '484', 'idDepartamento' => ' 12', 'nombre' => 'Tadó']);
		Ciudad::create(['id' => '485', 'idDepartamento' => ' 12', 'nombre' => 'Unguía']);
		Ciudad::create(['id' => '486', 'idDepartamento' => ' 12', 'nombre' => 'Unión Panamericana (ÁNIMAS)']);
		Ciudad::create(['id' => '487', 'idDepartamento' => ' 13', 'nombre' => 'Ayapel']);
		Ciudad::create(['id' => '488', 'idDepartamento' => ' 13', 'nombre' => 'Buenavista']);
		Ciudad::create(['id' => '489', 'idDepartamento' => ' 13', 'nombre' => 'Canalete']);
		Ciudad::create(['id' => '490', 'idDepartamento' => ' 13', 'nombre' => 'Cereté']);
		Ciudad::create(['id' => '491', 'idDepartamento' => ' 13', 'nombre' => 'Chimá']);
		Ciudad::create(['id' => '492', 'idDepartamento' => ' 13', 'nombre' => 'Chinú']);
		Ciudad::create(['id' => '493', 'idDepartamento' => ' 13', 'nombre' => 'Ciénaga de Oro']);
		Ciudad::create(['id' => '494', 'idDepartamento' => ' 13', 'nombre' => 'Cotorra']);
		Ciudad::create(['id' => '495', 'idDepartamento' => ' 13', 'nombre' => 'La Apartada y La Frontera']);
		Ciudad::create(['id' => '496', 'idDepartamento' => ' 13', 'nombre' => 'Lorica']);
		Ciudad::create(['id' => '497', 'idDepartamento' => ' 13', 'nombre' => 'Los Córdobas']);
		Ciudad::create(['id' => '498', 'idDepartamento' => ' 13', 'nombre' => 'Momil']);
		Ciudad::create(['id' => '499', 'idDepartamento' => ' 13', 'nombre' => 'Montelíbano']);
		Ciudad::create(['id' => '500', 'idDepartamento' => ' 13', 'nombre' => 'Monteria']);
		Ciudad::create(['id' => '501', 'idDepartamento' => ' 13', 'nombre' => 'Moñitos']);
		Ciudad::create(['id' => '502', 'idDepartamento' => ' 13', 'nombre' => 'Planeta Rica']);
		Ciudad::create(['id' => '503', 'idDepartamento' => ' 13', 'nombre' => 'Pueblo Nuevo']);
		Ciudad::create(['id' => '504', 'idDepartamento' => ' 13', 'nombre' => 'Puerto Escondido']);
		Ciudad::create(['id' => '505', 'idDepartamento' => ' 13', 'nombre' => 'Puerto Libertador']);
		Ciudad::create(['id' => '506', 'idDepartamento' => ' 13', 'nombre' => 'Purísima']);
		Ciudad::create(['id' => '507', 'idDepartamento' => ' 13', 'nombre' => 'Sahagún']);
		Ciudad::create(['id' => '508', 'idDepartamento' => ' 13', 'nombre' => 'San Andrés Sotavento']);
		Ciudad::create(['id' => '509', 'idDepartamento' => ' 13', 'nombre' => 'San Antero']);
		Ciudad::create(['id' => '510', 'idDepartamento' => ' 13', 'nombre' => 'San Bernardo del Viento']);
		Ciudad::create(['id' => '511', 'idDepartamento' => ' 13', 'nombre' => 'San Carlos']);
		Ciudad::create(['id' => '512', 'idDepartamento' => ' 13', 'nombre' => 'San José de Uré']);
		Ciudad::create(['id' => '513', 'idDepartamento' => ' 13', 'nombre' => 'San Pelayo']);
		Ciudad::create(['id' => '514', 'idDepartamento' => ' 13', 'nombre' => 'Tierralta']);
		Ciudad::create(['id' => '515', 'idDepartamento' => ' 13', 'nombre' => 'Tuchín']);
		Ciudad::create(['id' => '516', 'idDepartamento' => ' 13', 'nombre' => 'Valencia']);
		Ciudad::create(['id' => '517', 'idDepartamento' => ' 14', 'nombre' => 'Agua de Dios']);
		Ciudad::create(['id' => '518', 'idDepartamento' => ' 14', 'nombre' => 'Albán']);
		Ciudad::create(['id' => '519', 'idDepartamento' => ' 14', 'nombre' => 'Anapoima']);
		Ciudad::create(['id' => '520', 'idDepartamento' => ' 14', 'nombre' => 'Anolaima']);
		Ciudad::create(['id' => '521', 'idDepartamento' => ' 14', 'nombre' => 'Apulo']);
		Ciudad::create(['id' => '522', 'idDepartamento' => ' 14', 'nombre' => 'Arbeláez']);
		Ciudad::create(['id' => '523', 'idDepartamento' => ' 14', 'nombre' => 'Beltrán']);
		Ciudad::create(['id' => '524', 'idDepartamento' => ' 14', 'nombre' => 'Bituima']);
		Ciudad::create(['id' => '525', 'idDepartamento' => ' 14', 'nombre' => 'Bogotá D.C.']);
		Ciudad::create(['id' => '526', 'idDepartamento' => ' 14', 'nombre' => 'Bojacá']);
		Ciudad::create(['id' => '527', 'idDepartamento' => ' 14', 'nombre' => 'Cabrera']);
		Ciudad::create(['id' => '528', 'idDepartamento' => ' 14', 'nombre' => 'Cachipay']);
		Ciudad::create(['id' => '529', 'idDepartamento' => ' 14', 'nombre' => 'Cajicá']);
		Ciudad::create(['id' => '530', 'idDepartamento' => ' 14', 'nombre' => 'Caparrapí']);
		Ciudad::create(['id' => '531', 'idDepartamento' => ' 14', 'nombre' => 'Carmen de Carupa']);
		Ciudad::create(['id' => '532', 'idDepartamento' => ' 14', 'nombre' => 'Chaguaní']);
		Ciudad::create(['id' => '533', 'idDepartamento' => ' 14', 'nombre' => 'Chipaque']);
		Ciudad::create(['id' => '534', 'idDepartamento' => ' 14', 'nombre' => 'Choachí']);
		Ciudad::create(['id' => '535', 'idDepartamento' => ' 14', 'nombre' => 'Chocontá']);
		Ciudad::create(['id' => '536', 'idDepartamento' => ' 14', 'nombre' => 'Chía']);
		Ciudad::create(['id' => '537', 'idDepartamento' => ' 14', 'nombre' => 'Cogua']);
		Ciudad::create(['id' => '538', 'idDepartamento' => ' 14', 'nombre' => 'Cota']);
		Ciudad::create(['id' => '539', 'idDepartamento' => ' 14', 'nombre' => 'Cucunubá']);
		Ciudad::create(['id' => '540', 'idDepartamento' => ' 14', 'nombre' => 'Cáqueza']);
		Ciudad::create(['id' => '541', 'idDepartamento' => ' 14', 'nombre' => 'El Colegio']);
		Ciudad::create(['id' => '542', 'idDepartamento' => ' 14', 'nombre' => 'El Peñón']);
		Ciudad::create(['id' => '543', 'idDepartamento' => ' 14', 'nombre' => 'El Rosal']);
		Ciudad::create(['id' => '544', 'idDepartamento' => ' 14', 'nombre' => 'Facatativá']);
		Ciudad::create(['id' => '545', 'idDepartamento' => ' 14', 'nombre' => 'Fosca']);
		Ciudad::create(['id' => '546', 'idDepartamento' => ' 14', 'nombre' => 'Funza']);
		Ciudad::create(['id' => '547', 'idDepartamento' => ' 14', 'nombre' => 'Fusagasugá']);
		Ciudad::create(['id' => '548', 'idDepartamento' => ' 14', 'nombre' => 'Fómeque']);
		Ciudad::create(['id' => '549', 'idDepartamento' => ' 14', 'nombre' => 'Fúquene']);
		Ciudad::create(['id' => '550', 'idDepartamento' => ' 14', 'nombre' => 'Gachalá']);
		Ciudad::create(['id' => '551', 'idDepartamento' => ' 14', 'nombre' => 'Gachancipá']);
		Ciudad::create(['id' => '552', 'idDepartamento' => ' 14', 'nombre' => 'Gachetá']);
		Ciudad::create(['id' => '553', 'idDepartamento' => ' 14', 'nombre' => 'Gama']);
		Ciudad::create(['id' => '554', 'idDepartamento' => ' 14', 'nombre' => 'Girardot']);
		Ciudad::create(['id' => '555', 'idDepartamento' => ' 14', 'nombre' => 'Granada']);
		Ciudad::create(['id' => '556', 'idDepartamento' => ' 14', 'nombre' => 'Guachetá']);
		Ciudad::create(['id' => '557', 'idDepartamento' => ' 14', 'nombre' => 'Guaduas']);
		Ciudad::create(['id' => '558', 'idDepartamento' => ' 14', 'nombre' => 'Guasca']);
		Ciudad::create(['id' => '559', 'idDepartamento' => ' 14', 'nombre' => 'Guataquí']);
		Ciudad::create(['id' => '560', 'idDepartamento' => ' 14', 'nombre' => 'Guatavita']);
		Ciudad::create(['id' => '561', 'idDepartamento' => ' 14', 'nombre' => 'Guayabal de Siquima']);
		Ciudad::create(['id' => '562', 'idDepartamento' => ' 14', 'nombre' => 'Guayabetal']);
		Ciudad::create(['id' => '563', 'idDepartamento' => ' 14', 'nombre' => 'Gutiérrez']);
		Ciudad::create(['id' => '564', 'idDepartamento' => ' 14', 'nombre' => 'Jerusalén']);
		Ciudad::create(['id' => '565', 'idDepartamento' => ' 14', 'nombre' => 'Junín']);
		Ciudad::create(['id' => '566', 'idDepartamento' => ' 14', 'nombre' => 'La Calera']);
		Ciudad::create(['id' => '567', 'idDepartamento' => ' 14', 'nombre' => 'La Mesa']);
		Ciudad::create(['id' => '568', 'idDepartamento' => ' 14', 'nombre' => 'La Palma']);
		Ciudad::create(['id' => '569', 'idDepartamento' => ' 14', 'nombre' => 'La Peña']);
		Ciudad::create(['id' => '570', 'idDepartamento' => ' 14', 'nombre' => 'La Vega']);
		Ciudad::create(['id' => '571', 'idDepartamento' => ' 14', 'nombre' => 'Lenguazaque']);
		Ciudad::create(['id' => '572', 'idDepartamento' => ' 14', 'nombre' => 'Machetá']);
		Ciudad::create(['id' => '573', 'idDepartamento' => ' 14', 'nombre' => 'Madrid']);
		Ciudad::create(['id' => '574', 'idDepartamento' => ' 14', 'nombre' => 'Manta']);
		Ciudad::create(['id' => '575', 'idDepartamento' => ' 14', 'nombre' => 'Medina']);
		Ciudad::create(['id' => '576', 'idDepartamento' => ' 14', 'nombre' => 'Mosquera']);
		Ciudad::create(['id' => '577', 'idDepartamento' => ' 14', 'nombre' => 'Nariño']);
		Ciudad::create(['id' => '578', 'idDepartamento' => ' 14', 'nombre' => 'Nemocón']);
		Ciudad::create(['id' => '579', 'idDepartamento' => ' 14', 'nombre' => 'Nilo']);
		Ciudad::create(['id' => '580', 'idDepartamento' => ' 14', 'nombre' => 'Nimaima']);
		Ciudad::create(['id' => '581', 'idDepartamento' => ' 14', 'nombre' => 'Nocaima']);
		Ciudad::create(['id' => '582', 'idDepartamento' => ' 14', 'nombre' => 'Pacho']);
		Ciudad::create(['id' => '583', 'idDepartamento' => ' 14', 'nombre' => 'Paime']);
		Ciudad::create(['id' => '584', 'idDepartamento' => ' 14', 'nombre' => 'Pandi']);
		Ciudad::create(['id' => '585', 'idDepartamento' => ' 14', 'nombre' => 'Paratebueno']);
		Ciudad::create(['id' => '586', 'idDepartamento' => ' 14', 'nombre' => 'Pasca']);
		Ciudad::create(['id' => '587', 'idDepartamento' => ' 14', 'nombre' => 'Puerto Salgar']);
		Ciudad::create(['id' => '588', 'idDepartamento' => ' 14', 'nombre' => 'Pulí']);
		Ciudad::create(['id' => '589', 'idDepartamento' => ' 14', 'nombre' => 'Quebradanegra']);
		Ciudad::create(['id' => '590', 'idDepartamento' => ' 14', 'nombre' => 'Quetame']);
		Ciudad::create(['id' => '591', 'idDepartamento' => ' 14', 'nombre' => 'Quipile']);
		Ciudad::create(['id' => '592', 'idDepartamento' => ' 14', 'nombre' => 'Ricaurte']);
		Ciudad::create(['id' => '593', 'idDepartamento' => ' 14', 'nombre' => 'San Antonio de Tequendama']);
		Ciudad::create(['id' => '594', 'idDepartamento' => ' 14', 'nombre' => 'San Bernardo']);
		Ciudad::create(['id' => '595', 'idDepartamento' => ' 14', 'nombre' => 'San Cayetano']);
		Ciudad::create(['id' => '596', 'idDepartamento' => ' 14', 'nombre' => 'San Francisco']);
		Ciudad::create(['id' => '597', 'idDepartamento' => ' 14', 'nombre' => 'San Juan de Río Seco']);
		Ciudad::create(['id' => '598', 'idDepartamento' => ' 14', 'nombre' => 'Sasaima']);
		Ciudad::create(['id' => '599', 'idDepartamento' => ' 14', 'nombre' => 'Sesquilé']);
		Ciudad::create(['id' => '600', 'idDepartamento' => ' 14', 'nombre' => 'Sibaté']);
		Ciudad::create(['id' => '601', 'idDepartamento' => ' 14', 'nombre' => 'Silvania']);
		Ciudad::create(['id' => '602', 'idDepartamento' => ' 14', 'nombre' => 'Simijaca']);
		Ciudad::create(['id' => '603', 'idDepartamento' => ' 14', 'nombre' => 'Soacha']);
		Ciudad::create(['id' => '604', 'idDepartamento' => ' 14', 'nombre' => 'Sopó']);
		Ciudad::create(['id' => '605', 'idDepartamento' => ' 14', 'nombre' => 'Subachoque']);
		Ciudad::create(['id' => '606', 'idDepartamento' => ' 14', 'nombre' => 'Suesca']);
		Ciudad::create(['id' => '607', 'idDepartamento' => ' 14', 'nombre' => 'Supatá']);
		Ciudad::create(['id' => '608', 'idDepartamento' => ' 14', 'nombre' => 'Susa']);
		Ciudad::create(['id' => '609', 'idDepartamento' => ' 14', 'nombre' => 'Sutatausa']);
		Ciudad::create(['id' => '610', 'idDepartamento' => ' 14', 'nombre' => 'Tabio']);
		Ciudad::create(['id' => '611', 'idDepartamento' => ' 14', 'nombre' => 'Tausa']);
		Ciudad::create(['id' => '612', 'idDepartamento' => ' 14', 'nombre' => 'Tena']);
		Ciudad::create(['id' => '613', 'idDepartamento' => ' 14', 'nombre' => 'Tenjo']);
		Ciudad::create(['id' => '614', 'idDepartamento' => ' 14', 'nombre' => 'Tibacuy']);
		Ciudad::create(['id' => '615', 'idDepartamento' => ' 14', 'nombre' => 'Tibirita']);
		Ciudad::create(['id' => '616', 'idDepartamento' => ' 14', 'nombre' => 'Tocaima']);
		Ciudad::create(['id' => '617', 'idDepartamento' => ' 14', 'nombre' => 'Tocancipá']);
		Ciudad::create(['id' => '618', 'idDepartamento' => ' 14', 'nombre' => 'Topaipí']);
		Ciudad::create(['id' => '619', 'idDepartamento' => ' 14', 'nombre' => 'Ubalá']);
		Ciudad::create(['id' => '620', 'idDepartamento' => ' 14', 'nombre' => 'Ubaque']);
		Ciudad::create(['id' => '621', 'idDepartamento' => ' 14', 'nombre' => 'Ubaté']);
		Ciudad::create(['id' => '622', 'idDepartamento' => ' 14', 'nombre' => 'Une']);
		Ciudad::create(['id' => '623', 'idDepartamento' => ' 14', 'nombre' => 'Venecia (Ospina Pérez)']);
		Ciudad::create(['id' => '624', 'idDepartamento' => ' 14', 'nombre' => 'Vergara']);
		Ciudad::create(['id' => '625', 'idDepartamento' => ' 14', 'nombre' => 'Viani']);
		Ciudad::create(['id' => '626', 'idDepartamento' => ' 14', 'nombre' => 'Villagómez']);
		Ciudad::create(['id' => '627', 'idDepartamento' => ' 14', 'nombre' => 'Villapinzón']);
		Ciudad::create(['id' => '628', 'idDepartamento' => ' 14', 'nombre' => 'Villeta']);
		Ciudad::create(['id' => '629', 'idDepartamento' => ' 14', 'nombre' => 'Viotá']);
		Ciudad::create(['id' => '630', 'idDepartamento' => ' 14', 'nombre' => 'Yacopí']);
		Ciudad::create(['id' => '631', 'idDepartamento' => ' 14', 'nombre' => 'Zipacón']);
		Ciudad::create(['id' => '632', 'idDepartamento' => ' 14', 'nombre' => 'Zipaquirá']);
		Ciudad::create(['id' => '633', 'idDepartamento' => ' 14', 'nombre' => 'Útica']);
		Ciudad::create(['id' => '634', 'idDepartamento' => ' 15', 'nombre' => 'Inírida']);
		Ciudad::create(['id' => '635', 'idDepartamento' => ' 16', 'nombre' => 'Calamar']);
		Ciudad::create(['id' => '636', 'idDepartamento' => ' 16', 'nombre' => 'El Retorno']);
		Ciudad::create(['id' => '637', 'idDepartamento' => ' 16', 'nombre' => 'Miraflores']);
		Ciudad::create(['id' => '638', 'idDepartamento' => ' 16', 'nombre' => 'San José del Guaviare']);
		Ciudad::create(['id' => '639', 'idDepartamento' => ' 17', 'nombre' => 'Acevedo']);
		Ciudad::create(['id' => '640', 'idDepartamento' => ' 17', 'nombre' => 'Agrado']);
		Ciudad::create(['id' => '641', 'idDepartamento' => ' 17', 'nombre' => 'Aipe']);
		Ciudad::create(['id' => '642', 'idDepartamento' => ' 17', 'nombre' => 'Algeciras']);
		Ciudad::create(['id' => '643', 'idDepartamento' => ' 17', 'nombre' => 'Altamira']);
		Ciudad::create(['id' => '644', 'idDepartamento' => ' 17', 'nombre' => 'Baraya']);
		Ciudad::create(['id' => '645', 'idDepartamento' => ' 17', 'nombre' => 'Campoalegre']);
		Ciudad::create(['id' => '646', 'idDepartamento' => ' 17', 'nombre' => 'Colombia']);
		Ciudad::create(['id' => '647', 'idDepartamento' => ' 17', 'nombre' => 'Elías']);
		Ciudad::create(['id' => '648', 'idDepartamento' => ' 17', 'nombre' => 'Garzón']);
		Ciudad::create(['id' => '649', 'idDepartamento' => ' 17', 'nombre' => 'Gigante']);
		Ciudad::create(['id' => '650', 'idDepartamento' => ' 17', 'nombre' => 'Guadalupe']);
		Ciudad::create(['id' => '651', 'idDepartamento' => ' 17', 'nombre' => 'Hobo']);
		Ciudad::create(['id' => '652', 'idDepartamento' => ' 17', 'nombre' => 'Isnos']);
		Ciudad::create(['id' => '653', 'idDepartamento' => ' 17', 'nombre' => 'La Argentina']);
		Ciudad::create(['id' => '654', 'idDepartamento' => ' 17', 'nombre' => 'La Plata']);
		Ciudad::create(['id' => '655', 'idDepartamento' => ' 17', 'nombre' => 'Neiva']);
		Ciudad::create(['id' => '656', 'idDepartamento' => ' 17', 'nombre' => 'Nátaga']);
		Ciudad::create(['id' => '657', 'idDepartamento' => ' 17', 'nombre' => 'Oporapa']);
		Ciudad::create(['id' => '658', 'idDepartamento' => ' 17', 'nombre' => 'Paicol']);
		Ciudad::create(['id' => '659', 'idDepartamento' => ' 17', 'nombre' => 'Palermo']);
		Ciudad::create(['id' => '660', 'idDepartamento' => ' 17', 'nombre' => 'Palestina']);
		Ciudad::create(['id' => '661', 'idDepartamento' => ' 17', 'nombre' => 'Pital']);
		Ciudad::create(['id' => '662', 'idDepartamento' => ' 17', 'nombre' => 'Pitalito']);
		Ciudad::create(['id' => '663', 'idDepartamento' => ' 17', 'nombre' => 'Rivera']);
		Ciudad::create(['id' => '664', 'idDepartamento' => ' 17', 'nombre' => 'Saladoblanco']);
		Ciudad::create(['id' => '665', 'idDepartamento' => ' 17', 'nombre' => 'San Agustín']);
		Ciudad::create(['id' => '666', 'idDepartamento' => ' 17', 'nombre' => 'Santa María']);
		Ciudad::create(['id' => '667', 'idDepartamento' => ' 17', 'nombre' => 'Suaza']);
		Ciudad::create(['id' => '668', 'idDepartamento' => ' 17', 'nombre' => 'Tarqui']);
		Ciudad::create(['id' => '669', 'idDepartamento' => ' 17', 'nombre' => 'Tello']);
		Ciudad::create(['id' => '670', 'idDepartamento' => ' 17', 'nombre' => 'Teruel']);
		Ciudad::create(['id' => '671', 'idDepartamento' => ' 17', 'nombre' => 'Tesalia']);
		Ciudad::create(['id' => '672', 'idDepartamento' => ' 17', 'nombre' => 'Timaná']);
		Ciudad::create(['id' => '673', 'idDepartamento' => ' 17', 'nombre' => 'Villavieja']);
		Ciudad::create(['id' => '674', 'idDepartamento' => ' 17', 'nombre' => 'Yaguará']);
		Ciudad::create(['id' => '675', 'idDepartamento' => ' 17', 'nombre' => 'Íquira']);
		Ciudad::create(['id' => '676', 'idDepartamento' => ' 18', 'nombre' => 'Albania']);
		Ciudad::create(['id' => '677', 'idDepartamento' => ' 18', 'nombre' => 'Barrancas']);
		Ciudad::create(['id' => '678', 'idDepartamento' => ' 18', 'nombre' => 'Dibulla']);
		Ciudad::create(['id' => '679', 'idDepartamento' => ' 18', 'nombre' => 'Distracción']);
		Ciudad::create(['id' => '680', 'idDepartamento' => ' 18', 'nombre' => 'El Molino']);
		Ciudad::create(['id' => '681', 'idDepartamento' => ' 18', 'nombre' => 'Fonseca']);
		Ciudad::create(['id' => '682', 'idDepartamento' => ' 18', 'nombre' => 'Hatonuevo']);
		Ciudad::create(['id' => '683', 'idDepartamento' => ' 18', 'nombre' => 'La Jagua del Pilar']);
		Ciudad::create(['id' => '684', 'idDepartamento' => ' 18', 'nombre' => 'Maicao']);
		Ciudad::create(['id' => '685', 'idDepartamento' => ' 18', 'nombre' => 'Manaure']);
		Ciudad::create(['id' => '686', 'idDepartamento' => ' 18', 'nombre' => 'Riohacha']);
		Ciudad::create(['id' => '687', 'idDepartamento' => ' 18', 'nombre' => 'San Juan del Cesar']);
		Ciudad::create(['id' => '688', 'idDepartamento' => ' 18', 'nombre' => 'Uribia']);
		Ciudad::create(['id' => '689', 'idDepartamento' => ' 18', 'nombre' => 'Urumita']);
		Ciudad::create(['id' => '690', 'idDepartamento' => ' 18', 'nombre' => 'Villanueva']);
		Ciudad::create(['id' => '691', 'idDepartamento' => ' 19', 'nombre' => 'Algarrobo']);
		Ciudad::create(['id' => '692', 'idDepartamento' => ' 19', 'nombre' => 'Aracataca']);
		Ciudad::create(['id' => '693', 'idDepartamento' => ' 19', 'nombre' => 'Ariguaní (El Difícil)']);
		Ciudad::create(['id' => '694', 'idDepartamento' => ' 19', 'nombre' => 'Cerro San Antonio']);
		Ciudad::create(['id' => '695', 'idDepartamento' => ' 19', 'nombre' => 'Chivolo']);
		Ciudad::create(['id' => '696', 'idDepartamento' => ' 19', 'nombre' => 'Ciénaga']);
		Ciudad::create(['id' => '697', 'idDepartamento' => ' 19', 'nombre' => 'Concordia']);
		Ciudad::create(['id' => '698', 'idDepartamento' => ' 19', 'nombre' => 'El Banco']);
		Ciudad::create(['id' => '699', 'idDepartamento' => ' 19', 'nombre' => 'El Piñon']);
		Ciudad::create(['id' => '700', 'idDepartamento' => ' 19', 'nombre' => 'El Retén']);
		Ciudad::create(['id' => '701', 'idDepartamento' => ' 19', 'nombre' => 'Fundación']);
		Ciudad::create(['id' => '702', 'idDepartamento' => ' 19', 'nombre' => 'Guamal']);
		Ciudad::create(['id' => '703', 'idDepartamento' => ' 19', 'nombre' => 'Nueva Granada']);
		Ciudad::create(['id' => '704', 'idDepartamento' => ' 19', 'nombre' => 'Pedraza']);
		Ciudad::create(['id' => '705', 'idDepartamento' => ' 19', 'nombre' => 'Pijiño']);
		Ciudad::create(['id' => '706', 'idDepartamento' => ' 19', 'nombre' => 'Pivijay']);
		Ciudad::create(['id' => '707', 'idDepartamento' => ' 19', 'nombre' => 'Plato']);
		Ciudad::create(['id' => '708', 'idDepartamento' => ' 19', 'nombre' => 'Puebloviejo']);
		Ciudad::create(['id' => '709', 'idDepartamento' => ' 19', 'nombre' => 'Remolino']);
		Ciudad::create(['id' => '710', 'idDepartamento' => ' 19', 'nombre' => 'Sabanas de San Angel (SAN ANGEL)']);
		Ciudad::create(['id' => '711', 'idDepartamento' => ' 19', 'nombre' => 'Salamina']);
		Ciudad::create(['id' => '712', 'idDepartamento' => ' 19', 'nombre' => 'San Sebastián de Buenavista']);
		Ciudad::create(['id' => '713', 'idDepartamento' => ' 19', 'nombre' => 'San Zenón']);
		Ciudad::create(['id' => '714', 'idDepartamento' => ' 19', 'nombre' => 'Santa Ana']);
		Ciudad::create(['id' => '715', 'idDepartamento' => ' 19', 'nombre' => 'Santa Bárbara de Pinto']);
		Ciudad::create(['id' => '716', 'idDepartamento' => ' 19', 'nombre' => 'Santa Marta']);
		Ciudad::create(['id' => '717', 'idDepartamento' => ' 19', 'nombre' => 'Sitionuevo']);
		Ciudad::create(['id' => '718', 'idDepartamento' => ' 19', 'nombre' => 'Tenerife']);
		Ciudad::create(['id' => '719', 'idDepartamento' => ' 19', 'nombre' => 'Zapayán (PUNTA DE PIEDRAS)']);
		Ciudad::create(['id' => '720', 'idDepartamento' => ' 19', 'nombre' => 'Zona Bananera (PRADO - SEVILLA)']);
		Ciudad::create(['id' => '721', 'idDepartamento' => ' 20', 'nombre' => 'Acacías']);
		Ciudad::create(['id' => '722', 'idDepartamento' => ' 20', 'nombre' => 'Barranca de Upía']);
		Ciudad::create(['id' => '723', 'idDepartamento' => ' 20', 'nombre' => 'Cabuyaro']);
		Ciudad::create(['id' => '724', 'idDepartamento' => ' 20', 'nombre' => 'Castilla la Nueva']);
		Ciudad::create(['id' => '725', 'idDepartamento' => ' 20', 'nombre' => 'Cubarral']);
		Ciudad::create(['id' => '726', 'idDepartamento' => ' 20', 'nombre' => 'Cumaral']);
		Ciudad::create(['id' => '727', 'idDepartamento' => ' 20', 'nombre' => 'El Calvario']);
		Ciudad::create(['id' => '728', 'idDepartamento' => ' 20', 'nombre' => 'El Castillo']);
		Ciudad::create(['id' => '729', 'idDepartamento' => ' 20', 'nombre' => 'El Dorado']);
		Ciudad::create(['id' => '730', 'idDepartamento' => ' 20', 'nombre' => 'Fuente de Oro']);
		Ciudad::create(['id' => '731', 'idDepartamento' => ' 20', 'nombre' => 'Granada']);
		Ciudad::create(['id' => '732', 'idDepartamento' => ' 20', 'nombre' => 'Guamal']);
		Ciudad::create(['id' => '733', 'idDepartamento' => ' 20', 'nombre' => 'La Macarena']);
		Ciudad::create(['id' => '734', 'idDepartamento' => ' 20', 'nombre' => 'Lejanías']);
		Ciudad::create(['id' => '735', 'idDepartamento' => ' 20', 'nombre' => 'Mapiripan']);
		Ciudad::create(['id' => '736', 'idDepartamento' => ' 20', 'nombre' => 'Mesetas']);
		Ciudad::create(['id' => '737', 'idDepartamento' => ' 20', 'nombre' => 'Puerto Concordia']);
		Ciudad::create(['id' => '738', 'idDepartamento' => ' 20', 'nombre' => 'Puerto Gaitán']);
		Ciudad::create(['id' => '739', 'idDepartamento' => ' 20', 'nombre' => 'Puerto Lleras']);
		Ciudad::create(['id' => '740', 'idDepartamento' => ' 20', 'nombre' => 'Puerto López']);
		Ciudad::create(['id' => '741', 'idDepartamento' => ' 20', 'nombre' => 'Puerto Rico']);
		Ciudad::create(['id' => '742', 'idDepartamento' => ' 20', 'nombre' => 'Restrepo']);
		Ciudad::create(['id' => '743', 'idDepartamento' => ' 20', 'nombre' => 'San Carlos de Guaroa']);
		Ciudad::create(['id' => '744', 'idDepartamento' => ' 20', 'nombre' => 'San Juan de Arama']);
		Ciudad::create(['id' => '745', 'idDepartamento' => ' 20', 'nombre' => 'San Juanito']);
		Ciudad::create(['id' => '746', 'idDepartamento' => ' 20', 'nombre' => 'San Martín']);
		Ciudad::create(['id' => '747', 'idDepartamento' => ' 20', 'nombre' => 'Uribe']);
		Ciudad::create(['id' => '748', 'idDepartamento' => ' 20', 'nombre' => 'Villavicencio']);
		Ciudad::create(['id' => '749', 'idDepartamento' => ' 20', 'nombre' => 'Vista Hermosa']);
		Ciudad::create(['id' => '750', 'idDepartamento' => ' 21', 'nombre' => 'Albán (San José)']);
		Ciudad::create(['id' => '751', 'idDepartamento' => ' 21', 'nombre' => 'Aldana']);
		Ciudad::create(['id' => '752', 'idDepartamento' => ' 21', 'nombre' => 'Ancuya']);
		Ciudad::create(['id' => '753', 'idDepartamento' => ' 21', 'nombre' => 'Arboleda (Berruecos)']);
		Ciudad::create(['id' => '754', 'idDepartamento' => ' 21', 'nombre' => 'Barbacoas']);
		Ciudad::create(['id' => '755', 'idDepartamento' => ' 21', 'nombre' => 'Belén']);
		Ciudad::create(['id' => '756', 'idDepartamento' => ' 21', 'nombre' => 'Buesaco']);
		Ciudad::create(['id' => '757', 'idDepartamento' => ' 21', 'nombre' => 'Chachaguí']);
		Ciudad::create(['id' => '758', 'idDepartamento' => ' 21', 'nombre' => 'Colón (Génova)']);
		Ciudad::create(['id' => '759', 'idDepartamento' => ' 21', 'nombre' => 'Consaca']);
		Ciudad::create(['id' => '760', 'idDepartamento' => ' 21', 'nombre' => 'Contadero']);
		Ciudad::create(['id' => '761', 'idDepartamento' => ' 21', 'nombre' => 'Cuaspud (Carlosama)']);
		Ciudad::create(['id' => '762', 'idDepartamento' => ' 21', 'nombre' => 'Cumbal']);
		Ciudad::create(['id' => '763', 'idDepartamento' => ' 21', 'nombre' => 'Cumbitara']);
		Ciudad::create(['id' => '764', 'idDepartamento' => ' 21', 'nombre' => 'Córdoba']);
		Ciudad::create(['id' => '765', 'idDepartamento' => ' 21', 'nombre' => 'El Charco']);
		Ciudad::create(['id' => '766', 'idDepartamento' => ' 21', 'nombre' => 'El Peñol']);
		Ciudad::create(['id' => '767', 'idDepartamento' => ' 21', 'nombre' => 'El Rosario']);
		Ciudad::create(['id' => '768', 'idDepartamento' => ' 21', 'nombre' => 'El Tablón de Gómez']);
		Ciudad::create(['id' => '769', 'idDepartamento' => ' 21', 'nombre' => 'El Tambo']);
		Ciudad::create(['id' => '770', 'idDepartamento' => ' 21', 'nombre' => 'Francisco Pizarro']);
		Ciudad::create(['id' => '771', 'idDepartamento' => ' 21', 'nombre' => 'Funes']);
		Ciudad::create(['id' => '772', 'idDepartamento' => ' 21', 'nombre' => 'Guachavés']);
		Ciudad::create(['id' => '773', 'idDepartamento' => ' 21', 'nombre' => 'Guachucal']);
		Ciudad::create(['id' => '774', 'idDepartamento' => ' 21', 'nombre' => 'Guaitarilla']);
		Ciudad::create(['id' => '775', 'idDepartamento' => ' 21', 'nombre' => 'Gualmatán']);
		Ciudad::create(['id' => '776', 'idDepartamento' => ' 21', 'nombre' => 'Iles']);
		Ciudad::create(['id' => '777', 'idDepartamento' => ' 21', 'nombre' => 'Imúes']);
		Ciudad::create(['id' => '778', 'idDepartamento' => ' 21', 'nombre' => 'Ipiales']);
		Ciudad::create(['id' => '779', 'idDepartamento' => ' 21', 'nombre' => 'La Cruz']);
		Ciudad::create(['id' => '780', 'idDepartamento' => ' 21', 'nombre' => 'La Florida']);
		Ciudad::create(['id' => '781', 'idDepartamento' => ' 21', 'nombre' => 'La Llanada']);
		Ciudad::create(['id' => '782', 'idDepartamento' => ' 21', 'nombre' => 'La Tola']);
		Ciudad::create(['id' => '783', 'idDepartamento' => ' 21', 'nombre' => 'La Unión']);
		Ciudad::create(['id' => '784', 'idDepartamento' => ' 21', 'nombre' => 'Leiva']);
		Ciudad::create(['id' => '785', 'idDepartamento' => ' 21', 'nombre' => 'Linares']);
		Ciudad::create(['id' => '786', 'idDepartamento' => ' 21', 'nombre' => 'Magüi (Payán)']);
		Ciudad::create(['id' => '787', 'idDepartamento' => ' 21', 'nombre' => 'Mallama (Piedrancha)']);
		Ciudad::create(['id' => '788', 'idDepartamento' => ' 21', 'nombre' => 'Mosquera']);
		Ciudad::create(['id' => '789', 'idDepartamento' => ' 21', 'nombre' => 'Nariño']);
		Ciudad::create(['id' => '790', 'idDepartamento' => ' 21', 'nombre' => 'Olaya Herrera']);
		Ciudad::create(['id' => '791', 'idDepartamento' => ' 21', 'nombre' => 'Ospina']);
		Ciudad::create(['id' => '792', 'idDepartamento' => ' 21', 'nombre' => 'Policarpa']);
		Ciudad::create(['id' => '793', 'idDepartamento' => ' 21', 'nombre' => 'Potosí']);
		Ciudad::create(['id' => '794', 'idDepartamento' => ' 21', 'nombre' => 'Providencia']);
		Ciudad::create(['id' => '795', 'idDepartamento' => ' 21', 'nombre' => 'Puerres']);
		Ciudad::create(['id' => '796', 'idDepartamento' => ' 21', 'nombre' => 'Pupiales']);
		Ciudad::create(['id' => '797', 'idDepartamento' => ' 21', 'nombre' => 'Ricaurte']);
		Ciudad::create(['id' => '798', 'idDepartamento' => ' 21', 'nombre' => 'Roberto Payán (San José)']);
		Ciudad::create(['id' => '799', 'idDepartamento' => ' 21', 'nombre' => 'Samaniego']);
		Ciudad::create(['id' => '800', 'idDepartamento' => ' 21', 'nombre' => 'San Bernardo']);
		Ciudad::create(['id' => '801', 'idDepartamento' => ' 21', 'nombre' => 'San Juan de Pasto']);
		Ciudad::create(['id' => '802', 'idDepartamento' => ' 21', 'nombre' => 'San Lorenzo']);
		Ciudad::create(['id' => '803', 'idDepartamento' => ' 21', 'nombre' => 'San Pablo']);
		Ciudad::create(['id' => '804', 'idDepartamento' => ' 21', 'nombre' => 'San Pedro de Cartago']);
		Ciudad::create(['id' => '805', 'idDepartamento' => ' 21', 'nombre' => 'Sandoná']);
		Ciudad::create(['id' => '806', 'idDepartamento' => ' 21', 'nombre' => 'Santa Bárbara (Iscuandé)']);
		Ciudad::create(['id' => '807', 'idDepartamento' => ' 21', 'nombre' => 'Sapuyes']);
		Ciudad::create(['id' => '808', 'idDepartamento' => ' 21', 'nombre' => 'Sotomayor (Los Andes)']);
		Ciudad::create(['id' => '809', 'idDepartamento' => ' 21', 'nombre' => 'Taminango']);
		Ciudad::create(['id' => '810', 'idDepartamento' => ' 21', 'nombre' => 'Tangua']);
		Ciudad::create(['id' => '811', 'idDepartamento' => ' 21', 'nombre' => 'Tumaco']);
		Ciudad::create(['id' => '812', 'idDepartamento' => ' 21', 'nombre' => 'Túquerres']);
		Ciudad::create(['id' => '813', 'idDepartamento' => ' 21', 'nombre' => 'Yacuanquer']);
		Ciudad::create(['id' => '814', 'idDepartamento' => ' 22', 'nombre' => 'Arboledas']);
		Ciudad::create(['id' => '815', 'idDepartamento' => ' 22', 'nombre' => 'Bochalema']);
		Ciudad::create(['id' => '816', 'idDepartamento' => ' 22', 'nombre' => 'Bucarasica']);
		Ciudad::create(['id' => '817', 'idDepartamento' => ' 22', 'nombre' => 'Chinácota']);
		Ciudad::create(['id' => '818', 'idDepartamento' => ' 22', 'nombre' => 'Chitagá']);
		Ciudad::create(['id' => '819', 'idDepartamento' => ' 22', 'nombre' => 'Convención']);
		Ciudad::create(['id' => '820', 'idDepartamento' => ' 22', 'nombre' => 'Cucutilla']);
		Ciudad::create(['id' => '821', 'idDepartamento' => ' 22', 'nombre' => 'Cáchira']);
		Ciudad::create(['id' => '822', 'idDepartamento' => ' 22', 'nombre' => 'Cácota']);
		Ciudad::create(['id' => '823', 'idDepartamento' => ' 22', 'nombre' => 'Cúcuta']);
		Ciudad::create(['id' => '824', 'idDepartamento' => ' 22', 'nombre' => 'Durania']);
		Ciudad::create(['id' => '825', 'idDepartamento' => ' 22', 'nombre' => 'El Carmen']);
		Ciudad::create(['id' => '826', 'idDepartamento' => ' 22', 'nombre' => 'El Tarra']);
		Ciudad::create(['id' => '827', 'idDepartamento' => ' 22', 'nombre' => 'El Zulia']);
		Ciudad::create(['id' => '828', 'idDepartamento' => ' 22', 'nombre' => 'Gramalote']);
		Ciudad::create(['id' => '829', 'idDepartamento' => ' 22', 'nombre' => 'Hacarí']);
		Ciudad::create(['id' => '830', 'idDepartamento' => ' 22', 'nombre' => 'Herrán']);
		Ciudad::create(['id' => '831', 'idDepartamento' => ' 22', 'nombre' => 'La Esperanza']);
		Ciudad::create(['id' => '832', 'idDepartamento' => ' 22', 'nombre' => 'La Playa']);
		Ciudad::create(['id' => '833', 'idDepartamento' => ' 22', 'nombre' => 'Labateca']);
		Ciudad::create(['id' => '834', 'idDepartamento' => ' 22', 'nombre' => 'Los Patios']);
		Ciudad::create(['id' => '835', 'idDepartamento' => ' 22', 'nombre' => 'Lourdes']);
		Ciudad::create(['id' => '836', 'idDepartamento' => ' 22', 'nombre' => 'Mutiscua']);
		Ciudad::create(['id' => '837', 'idDepartamento' => ' 22', 'nombre' => 'Ocaña']);
		Ciudad::create(['id' => '838', 'idDepartamento' => ' 22', 'nombre' => 'Pamplona']);
		Ciudad::create(['id' => '839', 'idDepartamento' => ' 22', 'nombre' => 'Pamplonita']);
		Ciudad::create(['id' => '840', 'idDepartamento' => ' 22', 'nombre' => 'Puerto Santander']);
		Ciudad::create(['id' => '841', 'idDepartamento' => ' 22', 'nombre' => 'Ragonvalia']);
		Ciudad::create(['id' => '842', 'idDepartamento' => ' 22', 'nombre' => 'Salazar']);
		Ciudad::create(['id' => '843', 'idDepartamento' => ' 22', 'nombre' => 'San Calixto']);
		Ciudad::create(['id' => '844', 'idDepartamento' => ' 22', 'nombre' => 'San Cayetano']);
		Ciudad::create(['id' => '845', 'idDepartamento' => ' 22', 'nombre' => 'Santiago']);
		Ciudad::create(['id' => '846', 'idDepartamento' => ' 22', 'nombre' => 'Sardinata']);
		Ciudad::create(['id' => '847', 'idDepartamento' => ' 22', 'nombre' => 'Silos']);
		Ciudad::create(['id' => '848', 'idDepartamento' => ' 22', 'nombre' => 'Teorama']);
		Ciudad::create(['id' => '849', 'idDepartamento' => ' 22', 'nombre' => 'Tibú']);
		Ciudad::create(['id' => '850', 'idDepartamento' => ' 22', 'nombre' => 'Toledo']);
		Ciudad::create(['id' => '851', 'idDepartamento' => ' 22', 'nombre' => 'Villa Caro']);
		Ciudad::create(['id' => '852', 'idDepartamento' => ' 22', 'nombre' => 'Villa del Rosario']);
		Ciudad::create(['id' => '853', 'idDepartamento' => ' 22', 'nombre' => 'Ábrego']);
		Ciudad::create(['id' => '854', 'idDepartamento' => ' 23', 'nombre' => 'Colón']);
		Ciudad::create(['id' => '855', 'idDepartamento' => ' 23', 'nombre' => 'Mocoa']);
		Ciudad::create(['id' => '856', 'idDepartamento' => ' 23', 'nombre' => 'Orito']);
		Ciudad::create(['id' => '857', 'idDepartamento' => ' 23', 'nombre' => 'Puerto Asís']);
		Ciudad::create(['id' => '858', 'idDepartamento' => ' 23', 'nombre' => 'Puerto Caicedo']);
		Ciudad::create(['id' => '859', 'idDepartamento' => ' 23', 'nombre' => 'Puerto Guzmán']);
		Ciudad::create(['id' => '860', 'idDepartamento' => ' 23', 'nombre' => 'Puerto Leguízamo']);
		Ciudad::create(['id' => '861', 'idDepartamento' => ' 23', 'nombre' => 'San Francisco']);
		Ciudad::create(['id' => '862', 'idDepartamento' => ' 23', 'nombre' => 'San Miguel']);
		Ciudad::create(['id' => '863', 'idDepartamento' => ' 23', 'nombre' => 'Santiago']);
		Ciudad::create(['id' => '864', 'idDepartamento' => ' 23', 'nombre' => 'Sibundoy']);
		Ciudad::create(['id' => '865', 'idDepartamento' => ' 23', 'nombre' => 'Valle del Guamuez']);
		Ciudad::create(['id' => '866', 'idDepartamento' => ' 23', 'nombre' => 'Villagarzón']);
		Ciudad::create(['id' => '867', 'idDepartamento' => ' 24', 'nombre' => 'Armenia']);
		Ciudad::create(['id' => '868', 'idDepartamento' => ' 24', 'nombre' => 'Buenavista']);
		Ciudad::create(['id' => '869', 'idDepartamento' => ' 24', 'nombre' => 'Calarcá']);
		Ciudad::create(['id' => '870', 'idDepartamento' => ' 24', 'nombre' => 'Circasia']);
		Ciudad::create(['id' => '871', 'idDepartamento' => ' 24', 'nombre' => 'Cordobá']);
		Ciudad::create(['id' => '872', 'idDepartamento' => ' 24', 'nombre' => 'Filandia']);
		Ciudad::create(['id' => '873', 'idDepartamento' => ' 24', 'nombre' => 'Génova']);
		Ciudad::create(['id' => '874', 'idDepartamento' => ' 24', 'nombre' => 'La Tebaida']);
		Ciudad::create(['id' => '875', 'idDepartamento' => ' 24', 'nombre' => 'Montenegro']);
		Ciudad::create(['id' => '876', 'idDepartamento' => ' 24', 'nombre' => 'Pijao']);
		Ciudad::create(['id' => '877', 'idDepartamento' => ' 24', 'nombre' => 'Quimbaya']);
		Ciudad::create(['id' => '878', 'idDepartamento' => ' 24', 'nombre' => 'Salento']);
		Ciudad::create(['id' => '879', 'idDepartamento' => ' 25', 'nombre' => 'Apía']);
		Ciudad::create(['id' => '880', 'idDepartamento' => ' 25', 'nombre' => 'Balboa']);
		Ciudad::create(['id' => '881', 'idDepartamento' => ' 25', 'nombre' => 'Belén de Umbría']);
		Ciudad::create(['id' => '882', 'idDepartamento' => ' 25', 'nombre' => 'Dos Quebradas']);
		Ciudad::create(['id' => '883', 'idDepartamento' => ' 25', 'nombre' => 'Guática']);
		Ciudad::create(['id' => '884', 'idDepartamento' => ' 25', 'nombre' => 'La Celia']);
		Ciudad::create(['id' => '885', 'idDepartamento' => ' 25', 'nombre' => 'La Virginia']);
		Ciudad::create(['id' => '886', 'idDepartamento' => ' 25', 'nombre' => 'Marsella']);
		Ciudad::create(['id' => '887', 'idDepartamento' => ' 25', 'nombre' => 'Mistrató']);
		Ciudad::create(['id' => '888', 'idDepartamento' => ' 25', 'nombre' => 'Pereira']);
		Ciudad::create(['id' => '889', 'idDepartamento' => ' 25', 'nombre' => 'Pueblo Rico']);
		Ciudad::create(['id' => '890', 'idDepartamento' => ' 25', 'nombre' => 'Quinchía']);
		Ciudad::create(['id' => '891', 'idDepartamento' => ' 25', 'nombre' => 'Santa Rosa de Cabal']);
		Ciudad::create(['id' => '892', 'idDepartamento' => ' 25', 'nombre' => 'Santuario']);
		Ciudad::create(['id' => '893', 'idDepartamento' => ' 26', 'nombre' => 'Providencia']);
		Ciudad::create(['id' => '894', 'idDepartamento' => ' 27', 'nombre' => 'Aguada']);
		Ciudad::create(['id' => '895', 'idDepartamento' => ' 27', 'nombre' => 'Albania']);
		Ciudad::create(['id' => '896', 'idDepartamento' => ' 27', 'nombre' => 'Aratoca']);
		Ciudad::create(['id' => '897', 'idDepartamento' => ' 27', 'nombre' => 'Barbosa']);
		Ciudad::create(['id' => '898', 'idDepartamento' => ' 27', 'nombre' => 'Barichara']);
		Ciudad::create(['id' => '899', 'idDepartamento' => ' 27', 'nombre' => 'Barrancabermeja']);
		Ciudad::create(['id' => '900', 'idDepartamento' => ' 27', 'nombre' => 'Betulia']);
		Ciudad::create(['id' => '901', 'idDepartamento' => ' 27', 'nombre' => 'Bolívar']);
		Ciudad::create(['id' => '902', 'idDepartamento' => ' 27', 'nombre' => 'Bucaramanga']);
		Ciudad::create(['id' => '903', 'idDepartamento' => ' 27', 'nombre' => 'Cabrera']);
		Ciudad::create(['id' => '904', 'idDepartamento' => ' 27', 'nombre' => 'California']);
		Ciudad::create(['id' => '905', 'idDepartamento' => ' 27', 'nombre' => 'Capitanejo']);
		Ciudad::create(['id' => '906', 'idDepartamento' => ' 27', 'nombre' => 'Carcasí']);
		Ciudad::create(['id' => '907', 'idDepartamento' => ' 27', 'nombre' => 'Cepita']);
		Ciudad::create(['id' => '908', 'idDepartamento' => ' 27', 'nombre' => 'Cerrito']);
		Ciudad::create(['id' => '909', 'idDepartamento' => ' 27', 'nombre' => 'Charalá']);
		Ciudad::create(['id' => '910', 'idDepartamento' => ' 27', 'nombre' => 'Charta']);
		Ciudad::create(['id' => '911', 'idDepartamento' => ' 27', 'nombre' => 'Chima']);
		Ciudad::create(['id' => '912', 'idDepartamento' => ' 27', 'nombre' => 'Chipatá']);
		Ciudad::create(['id' => '913', 'idDepartamento' => ' 27', 'nombre' => 'Cimitarra']);
		Ciudad::create(['id' => '914', 'idDepartamento' => ' 27', 'nombre' => 'Concepción']);
		Ciudad::create(['id' => '915', 'idDepartamento' => ' 27', 'nombre' => 'Confines']);
		Ciudad::create(['id' => '916', 'idDepartamento' => ' 27', 'nombre' => 'Contratación']);
		Ciudad::create(['id' => '917', 'idDepartamento' => ' 27', 'nombre' => 'Coromoro']);
		Ciudad::create(['id' => '918', 'idDepartamento' => ' 27', 'nombre' => 'Curití']);
		Ciudad::create(['id' => '919', 'idDepartamento' => ' 27', 'nombre' => 'El Carmen']);
		Ciudad::create(['id' => '920', 'idDepartamento' => ' 27', 'nombre' => 'El Guacamayo']);
		Ciudad::create(['id' => '921', 'idDepartamento' => ' 27', 'nombre' => 'El Peñon']);
		Ciudad::create(['id' => '922', 'idDepartamento' => ' 27', 'nombre' => 'El Playón']);
		Ciudad::create(['id' => '923', 'idDepartamento' => ' 27', 'nombre' => 'Encino']);
		Ciudad::create(['id' => '924', 'idDepartamento' => ' 27', 'nombre' => 'Enciso']);
		Ciudad::create(['id' => '925', 'idDepartamento' => ' 27', 'nombre' => 'Floridablanca']);
		Ciudad::create(['id' => '926', 'idDepartamento' => ' 27', 'nombre' => 'Florián']);
		Ciudad::create(['id' => '927', 'idDepartamento' => ' 27', 'nombre' => 'Galán']);
		Ciudad::create(['id' => '928', 'idDepartamento' => ' 27', 'nombre' => 'Girón']);
		Ciudad::create(['id' => '929', 'idDepartamento' => ' 27', 'nombre' => 'Guaca']);
		Ciudad::create(['id' => '930', 'idDepartamento' => ' 27', 'nombre' => 'Guadalupe']);
		Ciudad::create(['id' => '931', 'idDepartamento' => ' 27', 'nombre' => 'Guapota']);
		Ciudad::create(['id' => '932', 'idDepartamento' => ' 27', 'nombre' => 'Guavatá']);
		Ciudad::create(['id' => '933', 'idDepartamento' => ' 27', 'nombre' => 'Guepsa']);
		Ciudad::create(['id' => '934', 'idDepartamento' => ' 27', 'nombre' => 'Gámbita']);
		Ciudad::create(['id' => '935', 'idDepartamento' => ' 27', 'nombre' => 'Hato']);
		Ciudad::create(['id' => '936', 'idDepartamento' => ' 27', 'nombre' => 'Jesús María']);
		Ciudad::create(['id' => '937', 'idDepartamento' => ' 27', 'nombre' => 'Jordán']);
		Ciudad::create(['id' => '938', 'idDepartamento' => ' 27', 'nombre' => 'La Belleza']);
		Ciudad::create(['id' => '939', 'idDepartamento' => ' 27', 'nombre' => 'La Paz']);
		Ciudad::create(['id' => '940', 'idDepartamento' => ' 27', 'nombre' => 'Landázuri']);
		Ciudad::create(['id' => '941', 'idDepartamento' => ' 27', 'nombre' => 'Lebrija']);
		Ciudad::create(['id' => '942', 'idDepartamento' => ' 27', 'nombre' => 'Los Santos']);
		Ciudad::create(['id' => '943', 'idDepartamento' => ' 27', 'nombre' => 'Macaravita']);
		Ciudad::create(['id' => '944', 'idDepartamento' => ' 27', 'nombre' => 'Matanza']);
		Ciudad::create(['id' => '945', 'idDepartamento' => ' 27', 'nombre' => 'Mogotes']);
		Ciudad::create(['id' => '946', 'idDepartamento' => ' 27', 'nombre' => 'Molagavita']);
		Ciudad::create(['id' => '947', 'idDepartamento' => ' 27', 'nombre' => 'Málaga']);
		Ciudad::create(['id' => '948', 'idDepartamento' => ' 27', 'nombre' => 'Ocamonte']);
		Ciudad::create(['id' => '949', 'idDepartamento' => ' 27', 'nombre' => 'Oiba']);
		Ciudad::create(['id' => '950', 'idDepartamento' => ' 27', 'nombre' => 'Onzaga']);
		Ciudad::create(['id' => '951', 'idDepartamento' => ' 27', 'nombre' => 'Palmar']);
		Ciudad::create(['id' => '952', 'idDepartamento' => ' 27', 'nombre' => 'Palmas del Socorro']);
		Ciudad::create(['id' => '953', 'idDepartamento' => ' 27', 'nombre' => 'Pie de Cuesta']);
		Ciudad::create(['id' => '954', 'idDepartamento' => ' 27', 'nombre' => 'Pinchote']);
		Ciudad::create(['id' => '955', 'idDepartamento' => ' 27', 'nombre' => 'Puente Nacional']);
		Ciudad::create(['id' => '956', 'idDepartamento' => ' 27', 'nombre' => 'Puerto Parra']);
		Ciudad::create(['id' => '957', 'idDepartamento' => ' 27', 'nombre' => 'Puerto Wilches']);
		Ciudad::create(['id' => '958', 'idDepartamento' => ' 27', 'nombre' => 'Páramo']);
		Ciudad::create(['id' => '959', 'idDepartamento' => ' 27', 'nombre' => 'Rio Negro']);
		Ciudad::create(['id' => '960', 'idDepartamento' => ' 27', 'nombre' => 'Sabana de Torres']);
		Ciudad::create(['id' => '961', 'idDepartamento' => ' 27', 'nombre' => 'San Andrés']);
		Ciudad::create(['id' => '962', 'idDepartamento' => ' 27', 'nombre' => 'San Benito']);
		Ciudad::create(['id' => '963', 'idDepartamento' => ' 27', 'nombre' => 'San Gíl']);
		Ciudad::create(['id' => '964', 'idDepartamento' => ' 27', 'nombre' => 'San Joaquín']);
		Ciudad::create(['id' => '965', 'idDepartamento' => ' 27', 'nombre' => 'San José de Miranda']);
		Ciudad::create(['id' => '966', 'idDepartamento' => ' 27', 'nombre' => 'San Miguel']);
		Ciudad::create(['id' => '967', 'idDepartamento' => ' 27', 'nombre' => 'San Vicente del Chucurí']);
		Ciudad::create(['id' => '968', 'idDepartamento' => ' 27', 'nombre' => 'Santa Bárbara']);
		Ciudad::create(['id' => '969', 'idDepartamento' => ' 27', 'nombre' => 'Santa Helena del Opón']);
		Ciudad::create(['id' => '970', 'idDepartamento' => ' 27', 'nombre' => 'Simacota']);
		Ciudad::create(['id' => '971', 'idDepartamento' => ' 27', 'nombre' => 'Socorro']);
		Ciudad::create(['id' => '972', 'idDepartamento' => ' 27', 'nombre' => 'Suaita']);
		Ciudad::create(['id' => '973', 'idDepartamento' => ' 27', 'nombre' => 'Sucre']);
		Ciudad::create(['id' => '974', 'idDepartamento' => ' 27', 'nombre' => 'Suratá']);
		Ciudad::create(['id' => '975', 'idDepartamento' => ' 27', 'nombre' => 'Tona']);
		Ciudad::create(['id' => '976', 'idDepartamento' => ' 27', 'nombre' => 'Valle de San José']);
		Ciudad::create(['id' => '977', 'idDepartamento' => ' 27', 'nombre' => 'Vetas']);
		Ciudad::create(['id' => '978', 'idDepartamento' => ' 27', 'nombre' => 'Villanueva']);
		Ciudad::create(['id' => '979', 'idDepartamento' => ' 27', 'nombre' => 'Vélez']);
		Ciudad::create(['id' => '980', 'idDepartamento' => ' 27', 'nombre' => 'Zapatoca']);
		Ciudad::create(['id' => '981', 'idDepartamento' => ' 28', 'nombre' => 'Buenavista']);
		Ciudad::create(['id' => '982', 'idDepartamento' => ' 28', 'nombre' => 'Caimito']);
		Ciudad::create(['id' => '983', 'idDepartamento' => ' 28', 'nombre' => 'Chalán']);
		Ciudad::create(['id' => '984', 'idDepartamento' => ' 28', 'nombre' => 'Colosó (Ricaurte)']);
		Ciudad::create(['id' => '985', 'idDepartamento' => ' 28', 'nombre' => 'Corozal']);
		Ciudad::create(['id' => '986', 'idDepartamento' => ' 28', 'nombre' => 'Coveñas']);
		Ciudad::create(['id' => '987', 'idDepartamento' => ' 28', 'nombre' => 'El Roble']);
		Ciudad::create(['id' => '988', 'idDepartamento' => ' 28', 'nombre' => 'Galeras (Nueva Granada)']);
		Ciudad::create(['id' => '989', 'idDepartamento' => ' 28', 'nombre' => 'Guaranda']);
		Ciudad::create(['id' => '990', 'idDepartamento' => ' 28', 'nombre' => 'La Unión']);
		Ciudad::create(['id' => '991', 'idDepartamento' => ' 28', 'nombre' => 'Los Palmitos']);
		Ciudad::create(['id' => '992', 'idDepartamento' => ' 28', 'nombre' => 'Majagual']);
		Ciudad::create(['id' => '993', 'idDepartamento' => ' 28', 'nombre' => 'Morroa']);
		Ciudad::create(['id' => '994', 'idDepartamento' => ' 28', 'nombre' => 'Ovejas']);
		Ciudad::create(['id' => '995', 'idDepartamento' => ' 28', 'nombre' => 'Palmito']);
		Ciudad::create(['id' => '996', 'idDepartamento' => ' 28', 'nombre' => 'Sampués']);
		Ciudad::create(['id' => '997', 'idDepartamento' => ' 28', 'nombre' => 'San Benito Abad']);
		Ciudad::create(['id' => '998', 'idDepartamento' => ' 28', 'nombre' => 'San Juan de Betulia']);
		Ciudad::create(['id' => '999', 'idDepartamento' => ' 28', 'nombre' => 'San Marcos']);
		Ciudad::create(['id' => '1000', 'idDepartamento' => ' 28', 'nombre' => 'San Onofre']);
		Ciudad::create(['id' => '1001', 'idDepartamento' => ' 28', 'nombre' => 'San Pedro']);
		Ciudad::create(['id' => '1002', 'idDepartamento' => ' 28', 'nombre' => 'Sincelejo']);
		Ciudad::create(['id' => '1003', 'idDepartamento' => ' 28', 'nombre' => 'Sincé']);
		Ciudad::create(['id' => '1004', 'idDepartamento' => ' 28', 'nombre' => 'Sucre']);
		Ciudad::create(['id' => '1005', 'idDepartamento' => ' 28', 'nombre' => 'Tolú']);
		Ciudad::create(['id' => '1006', 'idDepartamento' => ' 28', 'nombre' => 'Tolú Viejo']);
		Ciudad::create(['id' => '1007', 'idDepartamento' => ' 29', 'nombre' => 'Alpujarra']);
		Ciudad::create(['id' => '1008', 'idDepartamento' => ' 29', 'nombre' => 'Alvarado']);
		Ciudad::create(['id' => '1009', 'idDepartamento' => ' 29', 'nombre' => 'Ambalema']);
		Ciudad::create(['id' => '1010', 'idDepartamento' => ' 29', 'nombre' => 'Anzoátegui']);
		Ciudad::create(['id' => '1011', 'idDepartamento' => ' 29', 'nombre' => 'Armero (Guayabal)']);
		Ciudad::create(['id' => '1012', 'idDepartamento' => ' 29', 'nombre' => 'Ataco']);
		Ciudad::create(['id' => '1013', 'idDepartamento' => ' 29', 'nombre' => 'Cajamarca']);
		Ciudad::create(['id' => '1014', 'idDepartamento' => ' 29', 'nombre' => 'Carmen de Apicalá']);
		Ciudad::create(['id' => '1015', 'idDepartamento' => ' 29', 'nombre' => 'Casabianca']);
		Ciudad::create(['id' => '1016', 'idDepartamento' => ' 29', 'nombre' => 'Chaparral']);
		Ciudad::create(['id' => '1017', 'idDepartamento' => ' 29', 'nombre' => 'Coello']);
		Ciudad::create(['id' => '1018', 'idDepartamento' => ' 29', 'nombre' => 'Coyaima']);
		Ciudad::create(['id' => '1019', 'idDepartamento' => ' 29', 'nombre' => 'Cunday']);
		Ciudad::create(['id' => '1020', 'idDepartamento' => ' 29', 'nombre' => 'Dolores']);
		Ciudad::create(['id' => '1021', 'idDepartamento' => ' 29', 'nombre' => 'Espinal']);
		Ciudad::create(['id' => '1022', 'idDepartamento' => ' 29', 'nombre' => 'Falan']);
		Ciudad::create(['id' => '1023', 'idDepartamento' => ' 29', 'nombre' => 'Flandes']);
		Ciudad::create(['id' => '1024', 'idDepartamento' => ' 29', 'nombre' => 'Fresno']);
		Ciudad::create(['id' => '1025', 'idDepartamento' => ' 29', 'nombre' => 'Guamo']);
		Ciudad::create(['id' => '1026', 'idDepartamento' => ' 29', 'nombre' => 'Herveo']);
		Ciudad::create(['id' => '1027', 'idDepartamento' => ' 29', 'nombre' => 'Honda']);
		Ciudad::create(['id' => '1028', 'idDepartamento' => ' 29', 'nombre' => 'Ibagué']);
		Ciudad::create(['id' => '1029', 'idDepartamento' => ' 29', 'nombre' => 'Icononzo']);
		Ciudad::create(['id' => '1030', 'idDepartamento' => ' 29', 'nombre' => 'Lérida']);
		Ciudad::create(['id' => '1031', 'idDepartamento' => ' 29', 'nombre' => 'Líbano']);
		Ciudad::create(['id' => '1032', 'idDepartamento' => ' 29', 'nombre' => 'Mariquita']);
		Ciudad::create(['id' => '1033', 'idDepartamento' => ' 29', 'nombre' => 'Melgar']);
		Ciudad::create(['id' => '1034', 'idDepartamento' => ' 29', 'nombre' => 'Murillo']);
		Ciudad::create(['id' => '1035', 'idDepartamento' => ' 29', 'nombre' => 'Natagaima']);
		Ciudad::create(['id' => '1036', 'idDepartamento' => ' 29', 'nombre' => 'Ortega']);
		Ciudad::create(['id' => '1037', 'idDepartamento' => ' 29', 'nombre' => 'Palocabildo']);
		Ciudad::create(['id' => '1038', 'idDepartamento' => ' 29', 'nombre' => 'Piedras']);
		Ciudad::create(['id' => '1039', 'idDepartamento' => ' 29', 'nombre' => 'Planadas']);
		Ciudad::create(['id' => '1040', 'idDepartamento' => ' 29', 'nombre' => 'Prado']);
		Ciudad::create(['id' => '1041', 'idDepartamento' => ' 29', 'nombre' => 'Purificación']);
		Ciudad::create(['id' => '1042', 'idDepartamento' => ' 29', 'nombre' => 'Rioblanco']);
		Ciudad::create(['id' => '1043', 'idDepartamento' => ' 29', 'nombre' => 'Roncesvalles']);
		Ciudad::create(['id' => '1044', 'idDepartamento' => ' 29', 'nombre' => 'Rovira']);
		Ciudad::create(['id' => '1045', 'idDepartamento' => ' 29', 'nombre' => 'Saldaña']);
		Ciudad::create(['id' => '1046', 'idDepartamento' => ' 29', 'nombre' => 'San Antonio']);
		Ciudad::create(['id' => '1047', 'idDepartamento' => ' 29', 'nombre' => 'San Luis']);
		Ciudad::create(['id' => '1048', 'idDepartamento' => ' 29', 'nombre' => 'Santa Isabel']);
		Ciudad::create(['id' => '1049', 'idDepartamento' => ' 29', 'nombre' => 'Suárez']);
		Ciudad::create(['id' => '1050', 'idDepartamento' => ' 29', 'nombre' => 'Valle de San Juan']);
		Ciudad::create(['id' => '1051', 'idDepartamento' => ' 29', 'nombre' => 'Venadillo']);
		Ciudad::create(['id' => '1052', 'idDepartamento' => ' 29', 'nombre' => 'Villahermosa']);
		Ciudad::create(['id' => '1053', 'idDepartamento' => ' 29', 'nombre' => 'Villarrica']);
		Ciudad::create(['id' => '1054', 'idDepartamento' => ' 30', 'nombre' => 'Alcalá']);
		Ciudad::create(['id' => '1055', 'idDepartamento' => ' 30', 'nombre' => 'Andalucía']);
		Ciudad::create(['id' => '1056', 'idDepartamento' => ' 30', 'nombre' => 'Ansermanuevo']);
		Ciudad::create(['id' => '1057', 'idDepartamento' => ' 30', 'nombre' => 'Argelia']);
		Ciudad::create(['id' => '1058', 'idDepartamento' => ' 30', 'nombre' => 'Bolívar']);
		Ciudad::create(['id' => '1059', 'idDepartamento' => ' 30', 'nombre' => 'Buenaventura']);
		Ciudad::create(['id' => '1060', 'idDepartamento' => ' 30', 'nombre' => 'Buga']);
		Ciudad::create(['id' => '1061', 'idDepartamento' => ' 30', 'nombre' => 'Bugalagrande']);
		Ciudad::create(['id' => '1062', 'idDepartamento' => ' 30', 'nombre' => 'Caicedonia']);
		Ciudad::create(['id' => '1063', 'idDepartamento' => ' 30', 'nombre' => 'Calima (Darién)']);
		Ciudad::create(['id' => '1064', 'idDepartamento' => ' 30', 'nombre' => 'Calí']);
		Ciudad::create(['id' => '1065', 'idDepartamento' => ' 30', 'nombre' => 'Candelaria']);
		Ciudad::create(['id' => '1066', 'idDepartamento' => ' 30', 'nombre' => 'Cartago']);
		Ciudad::create(['id' => '1067', 'idDepartamento' => ' 30', 'nombre' => 'Dagua']);
		Ciudad::create(['id' => '1068', 'idDepartamento' => ' 30', 'nombre' => 'El Cairo']);
		Ciudad::create(['id' => '1069', 'idDepartamento' => ' 30', 'nombre' => 'El Cerrito']);
		Ciudad::create(['id' => '1070', 'idDepartamento' => ' 30', 'nombre' => 'El Dovio']);
		Ciudad::create(['id' => '1071', 'idDepartamento' => ' 30', 'nombre' => 'El Águila']);
		Ciudad::create(['id' => '1072', 'idDepartamento' => ' 30', 'nombre' => 'Florida']);
		Ciudad::create(['id' => '1073', 'idDepartamento' => ' 30', 'nombre' => 'Ginebra']);
		Ciudad::create(['id' => '1074', 'idDepartamento' => ' 30', 'nombre' => 'Guacarí']);
		Ciudad::create(['id' => '1075', 'idDepartamento' => ' 30', 'nombre' => 'Jamundí']);
		Ciudad::create(['id' => '1076', 'idDepartamento' => ' 30', 'nombre' => 'La Cumbre']);
		Ciudad::create(['id' => '1077', 'idDepartamento' => ' 30', 'nombre' => 'La Unión']);
		Ciudad::create(['id' => '1078', 'idDepartamento' => ' 30', 'nombre' => 'La Victoria']);
		Ciudad::create(['id' => '1079', 'idDepartamento' => ' 30', 'nombre' => 'Obando']);
		Ciudad::create(['id' => '1080', 'idDepartamento' => ' 30', 'nombre' => 'Palmira']);
		Ciudad::create(['id' => '1081', 'idDepartamento' => ' 30', 'nombre' => 'Pradera']);
		Ciudad::create(['id' => '1082', 'idDepartamento' => ' 30', 'nombre' => 'Restrepo']);
		Ciudad::create(['id' => '1083', 'idDepartamento' => ' 30', 'nombre' => 'Riofrío']);
		Ciudad::create(['id' => '1084', 'idDepartamento' => ' 30', 'nombre' => 'Roldanillo']);
		Ciudad::create(['id' => '1085', 'idDepartamento' => ' 30', 'nombre' => 'San Pedro']);
		Ciudad::create(['id' => '1086', 'idDepartamento' => ' 30', 'nombre' => 'Sevilla']);
		Ciudad::create(['id' => '1087', 'idDepartamento' => ' 30', 'nombre' => 'Toro']);
		Ciudad::create(['id' => '1088', 'idDepartamento' => ' 30', 'nombre' => 'Trujillo']);
		Ciudad::create(['id' => '1089', 'idDepartamento' => ' 30', 'nombre' => 'Tuluá']);
		Ciudad::create(['id' => '1090', 'idDepartamento' => ' 30', 'nombre' => 'Ulloa']);
		Ciudad::create(['id' => '1091', 'idDepartamento' => ' 30', 'nombre' => 'Versalles']);
		Ciudad::create(['id' => '1092', 'idDepartamento' => ' 30', 'nombre' => 'Vijes']);
		Ciudad::create(['id' => '1093', 'idDepartamento' => ' 30', 'nombre' => 'Yotoco']);
		Ciudad::create(['id' => '1094', 'idDepartamento' => ' 30', 'nombre' => 'Yumbo']);
		Ciudad::create(['id' => '1095', 'idDepartamento' => ' 30', 'nombre' => 'Zarzal']);
		Ciudad::create(['id' => '1096', 'idDepartamento' => ' 31', 'nombre' => 'Carurú']);
		Ciudad::create(['id' => '1097', 'idDepartamento' => ' 31', 'nombre' => 'Mitú']);
		Ciudad::create(['id' => '1098', 'idDepartamento' => ' 31', 'nombre' => 'Taraira']);
		Ciudad::create(['id' => '1099', 'idDepartamento' => ' 32', 'nombre' => 'Cumaribo']);
		Ciudad::create(['id' => '1100', 'idDepartamento' => ' 32', 'nombre' => 'La Primavera']);
		Ciudad::create(['id' => '1101', 'idDepartamento' => ' 32', 'nombre' => 'Puerto Carreño']);
		Ciudad::create(['id' => '1102', 'idDepartamento' => ' 32', 'nombre' => 'Santa Rosalía']);
    }
}
